INSERT INTO Boundaries VALUES("Afghanistan", "China", 91);
INSERT INTO Boundaries VALUES("Afghanistan", "Iran", 921);
INSERT INTO Boundaries VALUES("Afghanistan", "Pakistan", 2670);
INSERT INTO Boundaries VALUES("Afghanistan", "Tajikistan", 1357);
INSERT INTO Boundaries VALUES("Afghanistan", "Turkmenistan", 804);
INSERT INTO Boundaries VALUES("Afghanistan", "Uzbekistan", 144);
INSERT INTO Boundaries VALUES("Akrotiri", "Cyprus", 48);
INSERT INTO Boundaries VALUES("Albania", "Greece", 212);
INSERT INTO Boundaries VALUES("Albania", "Kosovo", 112);
INSERT INTO Boundaries VALUES("Albania", "Macedonia", 181);
INSERT INTO Boundaries VALUES("Albania", "Montenegro", 186);
INSERT INTO Boundaries VALUES("Algeria", "Libya", 989);
INSERT INTO Boundaries VALUES("Algeria", "Mali", 1359);
INSERT INTO Boundaries VALUES("Algeria", "Mauritania", 460);
INSERT INTO Boundaries VALUES("Algeria", "Morocco", 1900);
INSERT INTO Boundaries VALUES("Algeria", "Niger", 951);
INSERT INTO Boundaries VALUES("Algeria", "Tunisia", 1034);
INSERT INTO Boundaries VALUES("Algeria", "Western Sahara", 41);
INSERT INTO Boundaries VALUES("Andorra", "France", 55);
INSERT INTO Boundaries VALUES("Andorra", "Spain", 63);
INSERT INTO Boundaries VALUES("Angola", "Democratic Republic of the Congo", 2646);
INSERT INTO Boundaries VALUES("Angola", "Republic of the Congo", 231);
INSERT INTO Boundaries VALUES("Angola", "Namibia", 1427);
INSERT INTO Boundaries VALUES("Angola", "Zambia", 1065);
INSERT INTO Boundaries VALUES("Argentina", "Bolivia", 942);
INSERT INTO Boundaries VALUES("Argentina", "Brazil", 1263);
INSERT INTO Boundaries VALUES("Argentina", "Chile", 6691);
INSERT INTO Boundaries VALUES("Argentina", "Paraguay", 2531);
INSERT INTO Boundaries VALUES("Argentina", "Uruguay", 541);
INSERT INTO Boundaries VALUES("Armenia", "Azerbaijan", 996);
INSERT INTO Boundaries VALUES("Armenia", "Georgia", 219);
INSERT INTO Boundaries VALUES("Armenia", "Iran", 44);
INSERT INTO Boundaries VALUES("Armenia", "Turkey", 311);
INSERT INTO Boundaries VALUES("Austria", "Czech Republic", 402);
INSERT INTO Boundaries VALUES("Austria", "Germany", 801);
INSERT INTO Boundaries VALUES("Austria", "Hungary", 321);
INSERT INTO Boundaries VALUES("Austria", "Italy", 404);
INSERT INTO Boundaries VALUES("Austria", "Liechtenstein", 34);
INSERT INTO Boundaries VALUES("Austria", "Slovakia", 105);
INSERT INTO Boundaries VALUES("Austria", "Slovenia", 299);
INSERT INTO Boundaries VALUES("Austria", "Switzerland", 158);
INSERT INTO Boundaries VALUES("Azerbaijan", "Armenia", 996);
INSERT INTO Boundaries VALUES("Azerbaijan", "Georgia", 428);
INSERT INTO Boundaries VALUES("Azerbaijan", "Iran", 689);
INSERT INTO Boundaries VALUES("Azerbaijan", "Russia", 338);
INSERT INTO Boundaries VALUES("Azerbaijan", "Turkey", 17);
INSERT INTO Boundaries VALUES("Bangladesh", "Burma", 271);
INSERT INTO Boundaries VALUES("Bangladesh", "India", 4142);
INSERT INTO Boundaries VALUES("Belarus", "Latvia", 161);
INSERT INTO Boundaries VALUES("Belarus", "Lithuania", 640);
INSERT INTO Boundaries VALUES("Belarus", "Poland", 375);
INSERT INTO Boundaries VALUES("Belarus", "Russia", 1312);
INSERT INTO Boundaries VALUES("Belarus", "Ukraine", 1111);
INSERT INTO Boundaries VALUES("Belgium", "France", 556);
INSERT INTO Boundaries VALUES("Belgium", "Germany", 133);
INSERT INTO Boundaries VALUES("Belgium", "Luxembourg", 130);
INSERT INTO Boundaries VALUES("Belgium", "Netherlands", 478);
INSERT INTO Boundaries VALUES("Belize", "Guatemala", 266);
INSERT INTO Boundaries VALUES("Belize", "Mexico", 276);
INSERT INTO Boundaries VALUES("Benin", "Burkina Faso", 386);
INSERT INTO Boundaries VALUES("Benin", "Niger", 277);
INSERT INTO Boundaries VALUES("Benin", "Nigeria", 809);
INSERT INTO Boundaries VALUES("Benin", "Togo", 651);
INSERT INTO Boundaries VALUES("Bhutan", "China", 477);
INSERT INTO Boundaries VALUES("Bhutan", "India", 659);
INSERT INTO Boundaries VALUES("Bolivia", "Argentina", 942);
INSERT INTO Boundaries VALUES("Bolivia", "Brazil", 3403);
INSERT INTO Boundaries VALUES("Bolivia", "Chile", 942);
INSERT INTO Boundaries VALUES("Bolivia", "Paraguay", 753);
INSERT INTO Boundaries VALUES("Bolivia", "Peru", 1212);
INSERT INTO Boundaries VALUES("Bosnia and Herzegovina", "Croatia", 956);
INSERT INTO Boundaries VALUES("Bosnia and Herzegovina", "Montenegro", 242);
INSERT INTO Boundaries VALUES("Bosnia and Herzegovina", "Serbia", 345);
INSERT INTO Boundaries VALUES("Botswana", "Namibia", 1544);
INSERT INTO Boundaries VALUES("Botswana", "South Africa", 1969);
INSERT INTO Boundaries VALUES("Botswana", "Zambia", 0.1);
INSERT INTO Boundaries VALUES("Botswana", "Zimbabwe", 834);
INSERT INTO Boundaries VALUES("Brazil", "Argentina", 1263);
INSERT INTO Boundaries VALUES("Brazil", "Bolivia", 3403);
INSERT INTO Boundaries VALUES("Brazil", "Colombia", 1790);
INSERT INTO Boundaries VALUES("Brazil", "French Guiana", 649);
INSERT INTO Boundaries VALUES("Brazil", "Guyana", 1308);
INSERT INTO Boundaries VALUES("Brazil", "Paraguay", 1371);
INSERT INTO Boundaries VALUES("Brazil", "Peru", 2659);
INSERT INTO Boundaries VALUES("Brazil", "Suriname", 515);
INSERT INTO Boundaries VALUES("Brazil", "Uruguay", 1050);
INSERT INTO Boundaries VALUES("Brazil", "Venezuela", 2137);
INSERT INTO Boundaries VALUES("Brunei", "Malaysia", 266);
INSERT INTO Boundaries VALUES("Bulgaria", "Greece", 472);
INSERT INTO Boundaries VALUES("Bulgaria", "Macedonia", 162);
INSERT INTO Boundaries VALUES("Bulgaria", "Romania", 605);
INSERT INTO Boundaries VALUES("Bulgaria", "Serbia", 344);
INSERT INTO Boundaries VALUES("Bulgaria", "Turkey", 223);
INSERT INTO Boundaries VALUES("Burkina Faso", "Benin", 386);
INSERT INTO Boundaries VALUES("Burkina Faso", "Cote d'Ivoire", 545);
INSERT INTO Boundaries VALUES("Burkina Faso", "Ghana", 602);
INSERT INTO Boundaries VALUES("Burkina Faso", "Mali", 1325);
INSERT INTO Boundaries VALUES("Burkina Faso", "Niger", 622);
INSERT INTO Boundaries VALUES("Burkina Faso", "Togo", 131);
INSERT INTO Boundaries VALUES("Burma", "Bangladesh", 271);
INSERT INTO Boundaries VALUES("Burma", "China", 2129);
INSERT INTO Boundaries VALUES("Burma", "India", 1468);
INSERT INTO Boundaries VALUES("Burma", "Laos", 238);
INSERT INTO Boundaries VALUES("Burma", "Thailand", 2416);
INSERT INTO Boundaries VALUES("Burundi", "Democratic Republic of the Congo", 236);
INSERT INTO Boundaries VALUES("Burundi", "Rwanda", 315);
INSERT INTO Boundaries VALUES("Burundi", "Tanzania", 589);
INSERT INTO Boundaries VALUES("Cambodia", "Laos", 555);
INSERT INTO Boundaries VALUES("Cambodia", "Thailand", 817);
INSERT INTO Boundaries VALUES("Cambodia", "Vietnam", 1158);
INSERT INTO Boundaries VALUES("Cameroon", "Central African Republic", 901);
INSERT INTO Boundaries VALUES("Cameroon", "Chad", 1116);
INSERT INTO Boundaries VALUES("Cameroon", "Republic of the Congo", 494);
INSERT INTO Boundaries VALUES("Cameroon", "Equatorial Guinea", 183);
INSERT INTO Boundaries VALUES("Cameroon", "Gabon", 349);
INSERT INTO Boundaries VALUES("Cameroon", "Nigeria", 1975);
INSERT INTO Boundaries VALUES("Canada", "US", 8893);
INSERT INTO Boundaries VALUES("Central African Republic", "Cameroon", 901);
INSERT INTO Boundaries VALUES("Central African Republic", "Chad", 1556);
INSERT INTO Boundaries VALUES("Central African Republic", "Democratic Republic of the Congo", 1747);
INSERT INTO Boundaries VALUES("Central African Republic", "Republic of the Congo", 487);
INSERT INTO Boundaries VALUES("Central African Republic", "South Sudan", 1055);
INSERT INTO Boundaries VALUES("Central African Republic", "Sudan", 174);
INSERT INTO Boundaries VALUES("Chad", "Cameroon", 1116);
INSERT INTO Boundaries VALUES("Chad", "Central African Republic", 1556);
INSERT INTO Boundaries VALUES("Chad", "Libya", 1050);
INSERT INTO Boundaries VALUES("Chad", "Niger", 1196);
INSERT INTO Boundaries VALUES("Chad", "Nigeria", 85);
INSERT INTO Boundaries VALUES("Chad", "Sudan", 1403);
INSERT INTO Boundaries VALUES("Chile", "Argentina", 6691);
INSERT INTO Boundaries VALUES("Chile", "Bolivia", 942);
INSERT INTO Boundaries VALUES("Chile", "Peru", 168);
INSERT INTO Boundaries VALUES("China", "Afghanistan", 91);
INSERT INTO Boundaries VALUES("China", "Bhutan", 477);
INSERT INTO Boundaries VALUES("China", "Burma", 2129);
INSERT INTO Boundaries VALUES("China", "India", 2659);
INSERT INTO Boundaries VALUES("China", "Kazakhstan", 1765);
INSERT INTO Boundaries VALUES("China", "North Korea", 1352);
INSERT INTO Boundaries VALUES("China", "Kyrgyzstan", 1063);
INSERT INTO Boundaries VALUES("China", "Laos", 475);
INSERT INTO Boundaries VALUES("China", "Mongolia", 4630);
INSERT INTO Boundaries VALUES("China", "Nepal", 1389);
INSERT INTO Boundaries VALUES("China", "Pakistan", 438);
INSERT INTO Boundaries VALUES("China", "Russia", 4139);
INSERT INTO Boundaries VALUES("China", "Tajikistan", 477);
INSERT INTO Boundaries VALUES("China", "Vietnam", 1297);
INSERT INTO Boundaries VALUES("Colombia", "Brazil", 1790);
INSERT INTO Boundaries VALUES("Colombia", "Ecuador", 708);
INSERT INTO Boundaries VALUES("Colombia", "Panama", 339);
INSERT INTO Boundaries VALUES("Colombia", "Peru", 1494);
INSERT INTO Boundaries VALUES("Colombia", "Venezuela", 2341);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "Angola", 2646);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "Burundi", 236);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "Central African Republic", 1747);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "Republic of the Congo", 1229);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "Rwanda", 221);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "South Sudan", 714);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "Tanzania", 479);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "Uganda", 877);
INSERT INTO Boundaries VALUES("Congo, Democratic Republic of the", "Zambia", 2332);
INSERT INTO Boundaries VALUES("Congo, Republic of the", "Angola", 231);
INSERT INTO Boundaries VALUES("Congo, Republic of the", "Cameroon", 494);
INSERT INTO Boundaries VALUES("Congo, Republic of the", "Central African Republic", 487);
INSERT INTO Boundaries VALUES("Congo, Republic of the", "Democratic Republic of the Congo", 1229);
INSERT INTO Boundaries VALUES("Congo, Republic of the", "Gabon", 2567);
INSERT INTO Boundaries VALUES("Costa Rica", "Nicaragua", 313);
INSERT INTO Boundaries VALUES("Costa Rica", "Panama", 348);
INSERT INTO Boundaries VALUES("Cote d'Ivoire", "Burkina Faso", 545);
INSERT INTO Boundaries VALUES("Cote d'Ivoire", "Ghana", 720);
INSERT INTO Boundaries VALUES("Cote d'Ivoire", "Guinea", 816);
INSERT INTO Boundaries VALUES("Cote d'Ivoire", "Liberia", 778);
INSERT INTO Boundaries VALUES("Cote d'Ivoire", "Mali", 599);
INSERT INTO Boundaries VALUES("Croatia", "Bosnia and Herzegovina", 956);
INSERT INTO Boundaries VALUES("Croatia", "Hungary", 348);
INSERT INTO Boundaries VALUES("Croatia", "Montenegro", 19);
INSERT INTO Boundaries VALUES("Croatia", "Serbia", 314);
INSERT INTO Boundaries VALUES("Croatia", "Slovenia", 600);
INSERT INTO Boundaries VALUES("Cuba", "US Naval Base at Guantanamo Bay", 29);
INSERT INTO Boundaries VALUES("Cyprus", "Akrotiri", 48);
INSERT INTO Boundaries VALUES("Cyprus", "Dhekelia", 108);
INSERT INTO Boundaries VALUES("Czech Republic", "Austria", 402);
INSERT INTO Boundaries VALUES("Czech Republic", "Germany", 704);
INSERT INTO Boundaries VALUES("Czech Republic", "Poland", 699);
INSERT INTO Boundaries VALUES("Czech Republic", "Slovakia", 241);
INSERT INTO Boundaries VALUES("Denmark", "Germany", 140);
INSERT INTO Boundaries VALUES("Dhekelia", "Cyprus", 108);
INSERT INTO Boundaries VALUES("Djibouti", "Eritrea", 125);
INSERT INTO Boundaries VALUES("Djibouti", "Ethiopia", 342);
INSERT INTO Boundaries VALUES("Djibouti", "Somalia", 61);
INSERT INTO Boundaries VALUES("Dominican Republic", "Haiti", 376);
INSERT INTO Boundaries VALUES("Ecuador", "Colombia", 708);
INSERT INTO Boundaries VALUES("Ecuador", "Peru", 1529);
INSERT INTO Boundaries VALUES("Egypt", "Gaza Strip", 13);
INSERT INTO Boundaries VALUES("Egypt", "Israel", 208);
INSERT INTO Boundaries VALUES("Egypt", "Libya", 1115);
INSERT INTO Boundaries VALUES("Egypt", "Sudan", 1276);
INSERT INTO Boundaries VALUES("El Salvador", "Guatemala", 199);
INSERT INTO Boundaries VALUES("El Salvador", "Honduras", 391);
INSERT INTO Boundaries VALUES("Equatorial Guinea", "Cameroon", 183);
INSERT INTO Boundaries VALUES("Equatorial Guinea", "Gabon", 345);
INSERT INTO Boundaries VALUES("Eritrea", "Djibouti", 125);
INSERT INTO Boundaries VALUES("Eritrea", "Ethiopia", 1033);
INSERT INTO Boundaries VALUES("Eritrea", "Sudan", 682);
INSERT INTO Boundaries VALUES("Estonia", "Latvia", 333);
INSERT INTO Boundaries VALUES("Estonia", "Russia", 324);
INSERT INTO Boundaries VALUES("Ethiopia", "Djibouti", 342);
INSERT INTO Boundaries VALUES("Ethiopia", "Eritrea", 1033);
INSERT INTO Boundaries VALUES("Ethiopia", "Kenya", 867);
INSERT INTO Boundaries VALUES("Ethiopia", "Somalia", 1640);
INSERT INTO Boundaries VALUES("Ethiopia", "South Sudan", 1299);
INSERT INTO Boundaries VALUES("Ethiopia", "Sudan", 744);
INSERT INTO Boundaries VALUES("European Union", "Albania", 282);
INSERT INTO Boundaries VALUES("European Union", "Andorra", 120.3);
INSERT INTO Boundaries VALUES("European Union", "Belarus", 1050);
INSERT INTO Boundaries VALUES("European Union", "Croatia", 999);
INSERT INTO Boundaries VALUES("European Union", "Holy See", 3.2);
INSERT INTO Boundaries VALUES("European Union", "Liechtenstein", 34.9);
INSERT INTO Boundaries VALUES("European Union", "Macedonia", 394);
INSERT INTO Boundaries VALUES("European Union", "Moldova", 450);
INSERT INTO Boundaries VALUES("European Union", "Monaco", 4.4);
INSERT INTO Boundaries VALUES("European Union", "Norway", 2348);
INSERT INTO Boundaries VALUES("European Union", "Russia", 2257);
INSERT INTO Boundaries VALUES("European Union", "San Marino", 39);
INSERT INTO Boundaries VALUES("European Union", "Serbia", 945);
INSERT INTO Boundaries VALUES("European Union", "Switzerland", 1811);
INSERT INTO Boundaries VALUES("European Union", "Turkey", 446);
INSERT INTO Boundaries VALUES("European Union", "Ukraine", 1257);
INSERT INTO Boundaries VALUES("Finland", "Norway", 709);
INSERT INTO Boundaries VALUES("Finland", "Sweden", 545);
INSERT INTO Boundaries VALUES("Finland", "Russia", 1309);
INSERT INTO Boundaries VALUES("France", "Andorra", 55);
INSERT INTO Boundaries VALUES("France", "Belgium", 556);
INSERT INTO Boundaries VALUES("France", "Germany", 418);
INSERT INTO Boundaries VALUES("France", "Italy", 476);
INSERT INTO Boundaries VALUES("France", "Luxembourg", 69);
INSERT INTO Boundaries VALUES("France", "Monaco", 6);
INSERT INTO Boundaries VALUES("France", "Spain", 646);
INSERT INTO Boundaries VALUES("France", "Switzerland", 525);
INSERT INTO Boundaries VALUES("Gabon", "Cameroon", 349);
INSERT INTO Boundaries VALUES("Gabon", "Republic of the Congo", 2567);
INSERT INTO Boundaries VALUES("Gabon", "Equatorial Guinea", 345);
INSERT INTO Boundaries VALUES("Gambia, The", "Senegal", 749);
INSERT INTO Boundaries VALUES("Gaza Strip", "Egypt", 13);
INSERT INTO Boundaries VALUES("Gaza Strip", "Israel", 59);
INSERT INTO Boundaries VALUES("Georgia", "Armenia", 219);
INSERT INTO Boundaries VALUES("Georgia", "Azerbaijan", 428);
INSERT INTO Boundaries VALUES("Georgia", "Russia", 894);
INSERT INTO Boundaries VALUES("Georgia", "Turkey", 273);
INSERT INTO Boundaries VALUES("Germany", "Austria", 801);
INSERT INTO Boundaries VALUES("Germany", "Belgium", 133);
INSERT INTO Boundaries VALUES("Germany", "Czech Republic", 704);
INSERT INTO Boundaries VALUES("Germany", "Denmark", 140);
INSERT INTO Boundaries VALUES("Germany", "France", 418);
INSERT INTO Boundaries VALUES("Germany", "Luxembourg", 128);
INSERT INTO Boundaries VALUES("Germany", "Netherlands", 575);
INSERT INTO Boundaries VALUES("Germany", "Poland", 447);
INSERT INTO Boundaries VALUES("Germany", "Switzerland", 348);
INSERT INTO Boundaries VALUES("Ghana", "Burkina Faso", 602);
INSERT INTO Boundaries VALUES("Ghana", "Cote d'Ivoire", 720);
INSERT INTO Boundaries VALUES("Ghana", "Togo", 1098);
INSERT INTO Boundaries VALUES("Gibraltar", "Spain", 1);
INSERT INTO Boundaries VALUES("Greece", "Albania", 212);
INSERT INTO Boundaries VALUES("Greece", "Bulgaria", 472);
INSERT INTO Boundaries VALUES("Greece", "Macedonia", 234);
INSERT INTO Boundaries VALUES("Greece", "Turkey", 192);
INSERT INTO Boundaries VALUES("Guatemala", "Belize", 266);
INSERT INTO Boundaries VALUES("Guatemala", "El Salvador", 199);
INSERT INTO Boundaries VALUES("Guatemala", "Honduras", 244);
INSERT INTO Boundaries VALUES("Guatemala", "Mexico", 958);
INSERT INTO Boundaries VALUES("Guinea", "Cote d'Ivoire", 816);
INSERT INTO Boundaries VALUES("Guinea", "Guinea-Bissau", 421);
INSERT INTO Boundaries VALUES("Guinea", "Liberia", 590);
INSERT INTO Boundaries VALUES("Guinea", "Mali", 1062);
INSERT INTO Boundaries VALUES("Guinea", "Senegal", 363);
INSERT INTO Boundaries VALUES("Guinea", "Sierra Leone", 794);
INSERT INTO Boundaries VALUES("Guinea-Bissau", "Guinea", 421);
INSERT INTO Boundaries VALUES("Guinea-Bissau", "Senegal", 341);
INSERT INTO Boundaries VALUES("Guyana", "Brazil", 1308);
INSERT INTO Boundaries VALUES("Guyana", "Suriname", 836);
INSERT INTO Boundaries VALUES("Guyana", "Venezuela", 789);
INSERT INTO Boundaries VALUES("Haiti", "Dominican Republic", 376);
INSERT INTO Boundaries VALUES("Holy See", "Italy", 3);
INSERT INTO Boundaries VALUES("Honduras", "Guatemala", 244);
INSERT INTO Boundaries VALUES("Honduras", "El Salvador", 391);
INSERT INTO Boundaries VALUES("Honduras", "Nicaragua", 940);
INSERT INTO Boundaries VALUES("Hong Kong", "China", 33);
INSERT INTO Boundaries VALUES("Hungary", "Austria", 321);
INSERT INTO Boundaries VALUES("Hungary", "Croatia", 348);
INSERT INTO Boundaries VALUES("Hungary", "Romania", 424);
INSERT INTO Boundaries VALUES("Hungary", "Serbia", 164);
INSERT INTO Boundaries VALUES("Hungary", "Slovakia", 627);
INSERT INTO Boundaries VALUES("Hungary", "Slovenia", 94);
INSERT INTO Boundaries VALUES("Hungary", "Ukraine", 128);
INSERT INTO Boundaries VALUES("India", "Bangladesh", 4142);
INSERT INTO Boundaries VALUES("India", "Bhutan", 659);
INSERT INTO Boundaries VALUES("India", "Burma", 1468);
INSERT INTO Boundaries VALUES("India", "China", 2659);
INSERT INTO Boundaries VALUES("India", "Nepal", 1770);
INSERT INTO Boundaries VALUES("India", "Pakistan", 3190);
INSERT INTO Boundaries VALUES("Indonesia", "Timor-Leste", 253);
INSERT INTO Boundaries VALUES("Indonesia", "Malaysia", 1881);
INSERT INTO Boundaries VALUES("Indonesia", "Papua New Guinea", 824);
INSERT INTO Boundaries VALUES("Iran", "Afghanistan", 921);
INSERT INTO Boundaries VALUES("Iran", "Armenia", 44);
INSERT INTO Boundaries VALUES("Iran", "Azerbaijan", 689);
INSERT INTO Boundaries VALUES("Iran", "Iraq", 1599);
INSERT INTO Boundaries VALUES("Iran", "Pakistan", 959);
INSERT INTO Boundaries VALUES("Iran", "Turkey", 534);
INSERT INTO Boundaries VALUES("Iran", "Turkmenistan", 1148);
INSERT INTO Boundaries VALUES("Iraq", "Iran", 1599);
INSERT INTO Boundaries VALUES("Iraq", "Jordan", 179);
INSERT INTO Boundaries VALUES("Iraq", "Kuwait", 254);
INSERT INTO Boundaries VALUES("Iraq", "Saudi Arabia", 811);
INSERT INTO Boundaries VALUES("Iraq", "Syria", 599);
INSERT INTO Boundaries VALUES("Iraq", "Turkey", 367);
INSERT INTO Boundaries VALUES("Ireland", "UK", 443);
INSERT INTO Boundaries VALUES("Israel", "Egypt", 208);
INSERT INTO Boundaries VALUES("Israel", "Gaza Strip", 59);
INSERT INTO Boundaries VALUES("Israel", "Jordan", 307);
INSERT INTO Boundaries VALUES("Israel", "Lebanon", 81);
INSERT INTO Boundaries VALUES("Israel", "Syria", 83);
INSERT INTO Boundaries VALUES("Israel", "West Bank", 330);
INSERT INTO Boundaries VALUES("Italy", "Austria", 404);
INSERT INTO Boundaries VALUES("Italy", "France", 476);
INSERT INTO Boundaries VALUES("Italy", "Holy See", 3);
INSERT INTO Boundaries VALUES("Italy", "San Marino", 37);
INSERT INTO Boundaries VALUES("Italy", "Slovenia", 218);
INSERT INTO Boundaries VALUES("Italy", "Switzerland", 698);
INSERT INTO Boundaries VALUES("Jordan", "Iraq", 179);
INSERT INTO Boundaries VALUES("Jordan", "Israel", 307);
INSERT INTO Boundaries VALUES("Jordan", "Saudi Arabia", 731);
INSERT INTO Boundaries VALUES("Jordan", "Syria", 379);
INSERT INTO Boundaries VALUES("Jordan", "West Bank", 148);
INSERT INTO Boundaries VALUES("Kazakhstan", "China", 1765);
INSERT INTO Boundaries VALUES("Kazakhstan", "Kyrgyzstan", 1212);
INSERT INTO Boundaries VALUES("Kazakhstan", "Russia", 7644);
INSERT INTO Boundaries VALUES("Kazakhstan", "Turkmenistan", 413);
INSERT INTO Boundaries VALUES("Kazakhstan", "Uzbekistan", 2330);
INSERT INTO Boundaries VALUES("Kenya", "Ethiopia", 867);
INSERT INTO Boundaries VALUES("Kenya", "Somalia", 684);
INSERT INTO Boundaries VALUES("Kenya", "South Sudan", 317);
INSERT INTO Boundaries VALUES("Kenya", "Tanzania", 775);
INSERT INTO Boundaries VALUES("Kenya", "Uganda", 814);
INSERT INTO Boundaries VALUES("Korea, North", "China", 1352);
INSERT INTO Boundaries VALUES("Korea, North", "South Korea", 237);
INSERT INTO Boundaries VALUES("Korea, North", "Russia", 18);
INSERT INTO Boundaries VALUES("Korea, South", "North Korea", 237);
INSERT INTO Boundaries VALUES("Kosovo", "Albania", 112);
INSERT INTO Boundaries VALUES("Kosovo", "Macedonia", 160);
INSERT INTO Boundaries VALUES("Kosovo", "Montenegro", 76);
INSERT INTO Boundaries VALUES("Kosovo", "Serbia", 366);
INSERT INTO Boundaries VALUES("Kuwait", "Iraq", 254);
INSERT INTO Boundaries VALUES("Kuwait", "Saudi Arabia", 221);
INSERT INTO Boundaries VALUES("Kyrgyzstan", "China", 1063);
INSERT INTO Boundaries VALUES("Kyrgyzstan", "Kazakhstan", 1212);
INSERT INTO Boundaries VALUES("Kyrgyzstan", "Tajikistan", 984);
INSERT INTO Boundaries VALUES("Kyrgyzstan", "Uzbekistan", 1314);
INSERT INTO Boundaries VALUES("Laos", "Burma", 238);
INSERT INTO Boundaries VALUES("Laos", "Cambodia", 555);
INSERT INTO Boundaries VALUES("Laos", "China", 475);
INSERT INTO Boundaries VALUES("Laos", "Thailand", 1845);
INSERT INTO Boundaries VALUES("Laos", "Vietnam", 2161);
INSERT INTO Boundaries VALUES("Latvia", "Belarus", 161);
INSERT INTO Boundaries VALUES("Latvia", "Estonia", 333);
INSERT INTO Boundaries VALUES("Latvia", "Lithuania", 544);
INSERT INTO Boundaries VALUES("Latvia", "Russia", 332);
INSERT INTO Boundaries VALUES("Lebanon", "Israel", 81);
INSERT INTO Boundaries VALUES("Lebanon", "Syria", 403);
INSERT INTO Boundaries VALUES("Lesotho", "South Africa", 1106);
INSERT INTO Boundaries VALUES("Liberia", "Guinea", 590);
INSERT INTO Boundaries VALUES("Liberia", "Cote d'Ivoire", 778);
INSERT INTO Boundaries VALUES("Liberia", "Sierra Leone", 299);
INSERT INTO Boundaries VALUES("Libya", "Algeria", 989);
INSERT INTO Boundaries VALUES("Libya", "Chad", 1050);
INSERT INTO Boundaries VALUES("Libya", "Egypt", 1115);
INSERT INTO Boundaries VALUES("Libya", "Niger", 342);
INSERT INTO Boundaries VALUES("Libya", "Sudan", 382);
INSERT INTO Boundaries VALUES("Libya", "Tunisia", 461);
INSERT INTO Boundaries VALUES("Liechtenstein", "Austria", 34);
INSERT INTO Boundaries VALUES("Liechtenstein", "Switzerland", 41);
INSERT INTO Boundaries VALUES("Lithuania", "Belarus", 640);
INSERT INTO Boundaries VALUES("Lithuania", "Latvia", 544);
INSERT INTO Boundaries VALUES("Lithuania", "Poland", 100);
INSERT INTO Boundaries VALUES("Lithuania", "Russia", 261);
INSERT INTO Boundaries VALUES("Luxembourg", "Belgium", 130);
INSERT INTO Boundaries VALUES("Luxembourg", "France", 69);
INSERT INTO Boundaries VALUES("Luxembourg", "Germany", 128);
INSERT INTO Boundaries VALUES("Macau", "China", 3);
INSERT INTO Boundaries VALUES("Macedonia", "Albania", 181);
INSERT INTO Boundaries VALUES("Macedonia", "Bulgaria", 162);
INSERT INTO Boundaries VALUES("Macedonia", "Greece", 234);
INSERT INTO Boundaries VALUES("Macedonia", "Kosovo", 160);
INSERT INTO Boundaries VALUES("Macedonia", "Serbia", 101);
INSERT INTO Boundaries VALUES("Malawi", "Mozambique", 1498);
INSERT INTO Boundaries VALUES("Malawi", "Tanzania", 512);
INSERT INTO Boundaries VALUES("Malawi", "Zambia", 847);
INSERT INTO Boundaries VALUES("Malaysia", "Brunei", 266);
INSERT INTO Boundaries VALUES("Malaysia", "Indonesia", 1881);
INSERT INTO Boundaries VALUES("Malaysia", "Thailand", 595);
INSERT INTO Boundaries VALUES("Mali", "Algeria", 1359);
INSERT INTO Boundaries VALUES("Mali", "Burkina Faso", 1325);
INSERT INTO Boundaries VALUES("Mali", "Cote d'Ivoire", 599);
INSERT INTO Boundaries VALUES("Mali", "Guinea", 1062);
INSERT INTO Boundaries VALUES("Mali", "Mauritania", 2236);
INSERT INTO Boundaries VALUES("Mali", "Niger", 838);
INSERT INTO Boundaries VALUES("Mali", "Senegal", 489);
INSERT INTO Boundaries VALUES("Mauritania", "Algeria", 460);
INSERT INTO Boundaries VALUES("Mauritania", "Mali", 2236);
INSERT INTO Boundaries VALUES("Mauritania", "Senegal", 742);
INSERT INTO Boundaries VALUES("Mauritania", "Western Sahara", 1564);
INSERT INTO Boundaries VALUES("Mexico", "Belize", 276);
INSERT INTO Boundaries VALUES("Mexico", "Guatemala", 958);
INSERT INTO Boundaries VALUES("Mexico", "US", 3155);
INSERT INTO Boundaries VALUES("Moldova", "Romania", 683);
INSERT INTO Boundaries VALUES("Moldova", "Ukraine", 1202);
INSERT INTO Boundaries VALUES("Monaco", "France", 6);
INSERT INTO Boundaries VALUES("Mongolia", "China", 4630);
INSERT INTO Boundaries VALUES("Mongolia", "Russia", 3452);
INSERT INTO Boundaries VALUES("Montenegro", "Albania", 186);
INSERT INTO Boundaries VALUES("Montenegro", "Bosnia and Herzegovina", 242);
INSERT INTO Boundaries VALUES("Montenegro", "Croatia", 19);
INSERT INTO Boundaries VALUES("Montenegro", "Kosovo", 76);
INSERT INTO Boundaries VALUES("Montenegro", "Serbia", 157);
INSERT INTO Boundaries VALUES("Morocco", "Algeria", 1900);
INSERT INTO Boundaries VALUES("Morocco", "Western Sahara", 444);
INSERT INTO Boundaries VALUES("Morocco", "Spain", 8);
INSERT INTO Boundaries VALUES("Mozambique", "Malawi", 1498);
INSERT INTO Boundaries VALUES("Mozambique", "South Africa", 496);
INSERT INTO Boundaries VALUES("Mozambique", "Swaziland", 108);
INSERT INTO Boundaries VALUES("Mozambique", "Tanzania", 840);
INSERT INTO Boundaries VALUES("Mozambique", "Zambia", 439);
INSERT INTO Boundaries VALUES("Mozambique", "Zimbabwe", 1402);
INSERT INTO Boundaries VALUES("Namibia", "Angola", 1427);
INSERT INTO Boundaries VALUES("Namibia", "Botswana", 1544);
INSERT INTO Boundaries VALUES("Namibia", "South Africa", 1005);
INSERT INTO Boundaries VALUES("Namibia", "Zambia", 244);
INSERT INTO Boundaries VALUES("Nepal", "China", 1389);
INSERT INTO Boundaries VALUES("Nepal", "India", 1770);
INSERT INTO Boundaries VALUES("Netherlands", "Belgium", 478);
INSERT INTO Boundaries VALUES("Netherlands", "Germany", 575);
INSERT INTO Boundaries VALUES("Nicaragua", "Costa Rica", 313);
INSERT INTO Boundaries VALUES("Nicaragua", "Honduras", 940);
INSERT INTO Boundaries VALUES("Niger", "Algeria", 951);
INSERT INTO Boundaries VALUES("Niger", "Benin", 277);
INSERT INTO Boundaries VALUES("Niger", "Burkina Faso", 622);
INSERT INTO Boundaries VALUES("Niger", "Chad", 1196);
INSERT INTO Boundaries VALUES("Niger", "Libya", 342);
INSERT INTO Boundaries VALUES("Niger", "Mali", 838);
INSERT INTO Boundaries VALUES("Niger", "Nigeria", 1608);
INSERT INTO Boundaries VALUES("Nigeria", "Benin", 809);
INSERT INTO Boundaries VALUES("Nigeria", "Cameroon", 1975);
INSERT INTO Boundaries VALUES("Nigeria", "Chad", 85);
INSERT INTO Boundaries VALUES("Nigeria", "Niger", 1608);
INSERT INTO Boundaries VALUES("Norway", "Finland", 709);
INSERT INTO Boundaries VALUES("Norway", "Sweden", 1666);
INSERT INTO Boundaries VALUES("Norway", "Russia", 191);
INSERT INTO Boundaries VALUES("Oman", "Saudi Arabia", 658);
INSERT INTO Boundaries VALUES("Oman", "UAE", 609);
INSERT INTO Boundaries VALUES("Oman", "Yemen", 294);
INSERT INTO Boundaries VALUES("Pakistan", "Afghanistan", 2670);
INSERT INTO Boundaries VALUES("Pakistan", "China", 438);
INSERT INTO Boundaries VALUES("Pakistan", "India", 3190);
INSERT INTO Boundaries VALUES("Pakistan", "Iran", 959);
INSERT INTO Boundaries VALUES("Panama", "Colombia", 339);
INSERT INTO Boundaries VALUES("Panama", "Costa Rica", 348);
INSERT INTO Boundaries VALUES("Papua New Guinea", "Indonesia", 824);
INSERT INTO Boundaries VALUES("Paraguay", "Argentina", 2531);
INSERT INTO Boundaries VALUES("Paraguay", "Bolivia", 753);
INSERT INTO Boundaries VALUES("Paraguay", "Brazil", 1371);
INSERT INTO Boundaries VALUES("Peru", "Bolivia", 1212);
INSERT INTO Boundaries VALUES("Peru", "Brazil", 2659);
INSERT INTO Boundaries VALUES("Peru", "Chile", 168);
INSERT INTO Boundaries VALUES("Peru", "Colombia", 1494);
INSERT INTO Boundaries VALUES("Peru", "Ecuador", 1529);
INSERT INTO Boundaries VALUES("Poland", "Belarus", 375);
INSERT INTO Boundaries VALUES("Poland", "Czech Republic", 699);
INSERT INTO Boundaries VALUES("Poland", "Germany", 447);
INSERT INTO Boundaries VALUES("Poland", "Lithuania", 100);
INSERT INTO Boundaries VALUES("Poland", "Russia", 209);
INSERT INTO Boundaries VALUES("Poland", "Slovakia", 517);
INSERT INTO Boundaries VALUES("Poland", "Ukraine", 498);
INSERT INTO Boundaries VALUES("Portugal", "Spain", 1224);
INSERT INTO Boundaries VALUES("Qatar", "Saudi Arabia", 87);
INSERT INTO Boundaries VALUES("Romania", "Bulgaria", 605);
INSERT INTO Boundaries VALUES("Romania", "Hungary", 424);
INSERT INTO Boundaries VALUES("Romania", "Moldova", 683);
INSERT INTO Boundaries VALUES("Romania", "Serbia", 531);
INSERT INTO Boundaries VALUES("Romania", "Ukraine", 601);
INSERT INTO Boundaries VALUES("Russia", "Azerbaijan", 338);
INSERT INTO Boundaries VALUES("Russia", "Belarus", 1312);
INSERT INTO Boundaries VALUES("Russia", "China", 4133);
INSERT INTO Boundaries VALUES("Russia", "Estonia", 324);
INSERT INTO Boundaries VALUES("Russia", "Finland", 1309);
INSERT INTO Boundaries VALUES("Russia", "Georgia", 894);
INSERT INTO Boundaries VALUES("Russia", "Kazakhstan", 7644);
INSERT INTO Boundaries VALUES("Russia", "North Korea", 18);
INSERT INTO Boundaries VALUES("Russia", "Latvia", 332);
INSERT INTO Boundaries VALUES("Russia", "Lithuania", 261);
INSERT INTO Boundaries VALUES("Russia", "Mongolia", 3452);
INSERT INTO Boundaries VALUES("Russia", "Norway", 191);
INSERT INTO Boundaries VALUES("Russia", "Poland", 209);
INSERT INTO Boundaries VALUES("Russia", "Ukraine", 1944);
INSERT INTO Boundaries VALUES("Rwanda", "Burundi", 315);
INSERT INTO Boundaries VALUES("Rwanda", "Democratic Republic of the Congo", 221);
INSERT INTO Boundaries VALUES("Rwanda", "Tanzania", 222);
INSERT INTO Boundaries VALUES("Rwanda", "Uganda", 172);
INSERT INTO Boundaries VALUES("Saint Martin", "Sint Maarten", 16);
INSERT INTO Boundaries VALUES("San Marino", "Italy", 37);
INSERT INTO Boundaries VALUES("Saudi Arabia", "Iraq", 811);
INSERT INTO Boundaries VALUES("Saudi Arabia", "Jordan", 731);
INSERT INTO Boundaries VALUES("Saudi Arabia", "Kuwait", 221);
INSERT INTO Boundaries VALUES("Saudi Arabia", "Oman", 658);
INSERT INTO Boundaries VALUES("Saudi Arabia", "Qatar", 87);
INSERT INTO Boundaries VALUES("Saudi Arabia", "UAE", 457);
INSERT INTO Boundaries VALUES("Saudi Arabia", "Yemen", 1307);
INSERT INTO Boundaries VALUES("Senegal", "The Gambia", 749);
INSERT INTO Boundaries VALUES("Senegal", "Guinea", 363);
INSERT INTO Boundaries VALUES("Senegal", "Guinea-Bissau", 341);
INSERT INTO Boundaries VALUES("Senegal", "Mali", 489);
INSERT INTO Boundaries VALUES("Senegal", "Mauritania", 742);
INSERT INTO Boundaries VALUES("Serbia", "Bosnia and Herzegovina", 345);
INSERT INTO Boundaries VALUES("Serbia", "Bulgaria", 344);
INSERT INTO Boundaries VALUES("Serbia", "Croatia", 314);
INSERT INTO Boundaries VALUES("Serbia", "Hungary", 164);
INSERT INTO Boundaries VALUES("Serbia", "Kosovo", 366);
INSERT INTO Boundaries VALUES("Serbia", "Macedonia", 101);
INSERT INTO Boundaries VALUES("Serbia", "Montenegro", 157);
INSERT INTO Boundaries VALUES("Serbia", "Romania", 531);
INSERT INTO Boundaries VALUES("Sierra Leone", "Guinea", 794);
INSERT INTO Boundaries VALUES("Sierra Leone", "Liberia", 299);
INSERT INTO Boundaries VALUES("Sint Maarten", "Saint Martin", 16);
INSERT INTO Boundaries VALUES("Slovakia", "Austria", 105);
INSERT INTO Boundaries VALUES("Slovakia", "Czech Republic", 241);
INSERT INTO Boundaries VALUES("Slovakia", "Hungary", 627);
INSERT INTO Boundaries VALUES("Slovakia", "Poland", 517);
INSERT INTO Boundaries VALUES("Slovakia", "Ukraine", 97);
INSERT INTO Boundaries VALUES("Slovenia", "Austria", 299);
INSERT INTO Boundaries VALUES("Slovenia", "Croatia", 600);
INSERT INTO Boundaries VALUES("Slovenia", "Hungary", 94);
INSERT INTO Boundaries VALUES("Slovenia", "Italy", 218);
INSERT INTO Boundaries VALUES("Somalia", "Djibouti", 61);
INSERT INTO Boundaries VALUES("Somalia", "Ethiopia", 1640);
INSERT INTO Boundaries VALUES("Somalia", "Kenya", 684);
INSERT INTO Boundaries VALUES("South Africa", "Botswana", 1969);
INSERT INTO Boundaries VALUES("South Africa", "Lesotho", 1106);
INSERT INTO Boundaries VALUES("South Africa", "Mozambique", 496);
INSERT INTO Boundaries VALUES("South Africa", "Namibia", 1005);
INSERT INTO Boundaries VALUES("South Africa", "Swaziland", 438);
INSERT INTO Boundaries VALUES("South Africa", "Zimbabwe", 230);
INSERT INTO Boundaries VALUES("South Sudan", "Central African Republic", 1055);
INSERT INTO Boundaries VALUES("South Sudan", "Democratic Republic of the Congo", 714);
INSERT INTO Boundaries VALUES("South Sudan", "Ethiopia", 1299);
INSERT INTO Boundaries VALUES("South Sudan", "Kenya", 317);
INSERT INTO Boundaries VALUES("South Sudan", "Sudan", 2158);
INSERT INTO Boundaries VALUES("South Sudan", "Uganda", 475);
INSERT INTO Boundaries VALUES("Spain", "Andorra", 63);
INSERT INTO Boundaries VALUES("Spain", "France", 646);
INSERT INTO Boundaries VALUES("Spain", "Gibraltar", 1);
INSERT INTO Boundaries VALUES("Spain", "Portugal", 1224);
INSERT INTO Boundaries VALUES("Spain", "Morocco", 8);
INSERT INTO Boundaries VALUES("Sudan", "Central African Republic", 174);
INSERT INTO Boundaries VALUES("Sudan", "Chad", 1403);
INSERT INTO Boundaries VALUES("Sudan", "Egypt", 1276);
INSERT INTO Boundaries VALUES("Sudan", "Eritrea", 682);
INSERT INTO Boundaries VALUES("Sudan", "Ethiopia", 744);
INSERT INTO Boundaries VALUES("Sudan", "Libya", 382);
INSERT INTO Boundaries VALUES("Sudan", "South Sudan", 2158);
INSERT INTO Boundaries VALUES("Suriname", "Brazil", 515);
INSERT INTO Boundaries VALUES("Suriname", "French Guiana", 556);
INSERT INTO Boundaries VALUES("Suriname", "Guyana", 836);
INSERT INTO Boundaries VALUES("Swaziland", "Mozambique", 108);
INSERT INTO Boundaries VALUES("Swaziland", "South Africa", 438);
INSERT INTO Boundaries VALUES("Sweden", "Finland", 545);
INSERT INTO Boundaries VALUES("Sweden", "Norway", 1666);
INSERT INTO Boundaries VALUES("Switzerland", "Austria", 158);
INSERT INTO Boundaries VALUES("Switzerland", "France", 525);
INSERT INTO Boundaries VALUES("Switzerland", "Italy", 698);
INSERT INTO Boundaries VALUES("Switzerland", "Liechtenstein", 41);
INSERT INTO Boundaries VALUES("Switzerland", "Germany", 348);
INSERT INTO Boundaries VALUES("Syria", "Iraq", 599);
INSERT INTO Boundaries VALUES("Syria", "Israel", 83);
INSERT INTO Boundaries VALUES("Syria", "Jordan", 379);
INSERT INTO Boundaries VALUES("Syria", "Lebanon", 403);
INSERT INTO Boundaries VALUES("Syria", "Turkey", 899);
INSERT INTO Boundaries VALUES("Tajikistan", "Afghanistan", 1357);
INSERT INTO Boundaries VALUES("Tajikistan", "China", 477);
INSERT INTO Boundaries VALUES("Tajikistan", "Kyrgyzstan", 984);
INSERT INTO Boundaries VALUES("Tajikistan", "Uzbekistan", 1312);
INSERT INTO Boundaries VALUES("Tanzania", "Burundi", 589);
INSERT INTO Boundaries VALUES("Tanzania", "Democratic Republic of the Congo", 479);
INSERT INTO Boundaries VALUES("Tanzania", "Kenya", 775);
INSERT INTO Boundaries VALUES("Tanzania", "Malawi", 512);
INSERT INTO Boundaries VALUES("Tanzania", "Mozambique", 840);
INSERT INTO Boundaries VALUES("Tanzania", "Rwanda", 222);
INSERT INTO Boundaries VALUES("Tanzania", "Uganda", 391);
INSERT INTO Boundaries VALUES("Tanzania", "Zambia", 353);
INSERT INTO Boundaries VALUES("Thailand", "Burma", 2416);
INSERT INTO Boundaries VALUES("Thailand", "Cambodia", 817);
INSERT INTO Boundaries VALUES("Thailand", "Laos", 1845);
INSERT INTO Boundaries VALUES("Thailand", "Malaysia", 595);
INSERT INTO Boundaries VALUES("Timor-Leste", "Indonesia", 253);
INSERT INTO Boundaries VALUES("Togo", "Benin", 651);
INSERT INTO Boundaries VALUES("Togo", "Burkina Faso", 131);
INSERT INTO Boundaries VALUES("Togo", "Ghana", 1098);
INSERT INTO Boundaries VALUES("Tunisia", "Algeria", 1034);
INSERT INTO Boundaries VALUES("Tunisia", "Libya", 461);
INSERT INTO Boundaries VALUES("Turkey", "Armenia", 311);
INSERT INTO Boundaries VALUES("Turkey", "Azerbaijan", 17);
INSERT INTO Boundaries VALUES("Turkey", "Bulgaria", 223);
INSERT INTO Boundaries VALUES("Turkey", "Georgia", 273);
INSERT INTO Boundaries VALUES("Turkey", "Greece", 192);
INSERT INTO Boundaries VALUES("Turkey", "Iran", 534);
INSERT INTO Boundaries VALUES("Turkey", "Iraq", 367);
INSERT INTO Boundaries VALUES("Turkey", "Syria", 899);
INSERT INTO Boundaries VALUES("Turkmenistan", "Afghanistan", 804);
INSERT INTO Boundaries VALUES("Turkmenistan", "Iran", 1148);
INSERT INTO Boundaries VALUES("Turkmenistan", "Kazakhstan", 413);
INSERT INTO Boundaries VALUES("Turkmenistan", "Uzbekistan", 1793);
INSERT INTO Boundaries VALUES("Uganda", "Democratic Republic of the Congo", 877);
INSERT INTO Boundaries VALUES("Uganda", "Kenya", 814);
INSERT INTO Boundaries VALUES("Uganda", "Rwanda", 172);
INSERT INTO Boundaries VALUES("Uganda", "South Sudan", 475);
INSERT INTO Boundaries VALUES("Uganda", "Tanzania", 391);
INSERT INTO Boundaries VALUES("Ukraine", "Belarus", 1111);
INSERT INTO Boundaries VALUES("Ukraine", "Hungary", 128);
INSERT INTO Boundaries VALUES("Ukraine", "Moldova", 1202);
INSERT INTO Boundaries VALUES("Ukraine", "Poland", 498);
INSERT INTO Boundaries VALUES("Ukraine", "Romania", 601);
INSERT INTO Boundaries VALUES("Ukraine", "Russia", 1944);
INSERT INTO Boundaries VALUES("Ukraine", "Slovakia", 97);
INSERT INTO Boundaries VALUES("United Arab Emirates", "Oman", 609);
INSERT INTO Boundaries VALUES("United Arab Emirates", "Saudi Arabia", 457);
INSERT INTO Boundaries VALUES("United Kingdom", "Ireland", 443);
INSERT INTO Boundaries VALUES("United States", "Canada", 8893);
INSERT INTO Boundaries VALUES("United States", "Mexico", 3155);
INSERT INTO Boundaries VALUES("Uruguay", "Argentina", 541);
INSERT INTO Boundaries VALUES("Uruguay", "Brazil", 1050);
INSERT INTO Boundaries VALUES("Uzbekistan", "Afghanistan", 144);
INSERT INTO Boundaries VALUES("Uzbekistan", "Kazakhstan", 2330);
INSERT INTO Boundaries VALUES("Uzbekistan", "Kyrgyzstan", 1314);
INSERT INTO Boundaries VALUES("Uzbekistan", "Tajikistan", 1312);
INSERT INTO Boundaries VALUES("Uzbekistan", "Turkmenistan", 1793);
INSERT INTO Boundaries VALUES("Venezuela", "Brazil", 2137);
INSERT INTO Boundaries VALUES("Venezuela", "Colombia", 2341);
INSERT INTO Boundaries VALUES("Venezuela", "Guyana", 789);
INSERT INTO Boundaries VALUES("Vietnam", "Cambodia", 1158);
INSERT INTO Boundaries VALUES("Vietnam", "China", 1297);
INSERT INTO Boundaries VALUES("Vietnam", "Laos", 2161);
INSERT INTO Boundaries VALUES("West Bank", "Israel", 330);
INSERT INTO Boundaries VALUES("West Bank", "Jordan", 148);
INSERT INTO Boundaries VALUES("Western Sahara", "Algeria", 41);
INSERT INTO Boundaries VALUES("Western Sahara", "Mauritania", 1564);
INSERT INTO Boundaries VALUES("Western Sahara", "Morocco", 444);
INSERT INTO Boundaries VALUES("Yemen", "Oman", 294);
INSERT INTO Boundaries VALUES("Yemen", "Saudi Arabia", 1307);
INSERT INTO Boundaries VALUES("Zambia", "Angola", 1065);
INSERT INTO Boundaries VALUES("Zambia", "Botswana", 0.1);
INSERT INTO Boundaries VALUES("Zambia", "Democratic Republic of the Congo", 2332);
INSERT INTO Boundaries VALUES("Zambia", "Malawi", 847);
INSERT INTO Boundaries VALUES("Zambia", "Mozambique", 439);
INSERT INTO Boundaries VALUES("Zambia", "Namibia", 244);
INSERT INTO Boundaries VALUES("Zambia", "Tanzania", 353);
INSERT INTO Boundaries VALUES("Zambia", "Zimbabwe", 763);
INSERT INTO Boundaries VALUES("Zimbabwe", "Botswana", 834);
INSERT INTO Boundaries VALUES("Zimbabwe", "Mozambique", 1402);
INSERT INTO Boundaries VALUES("Zimbabwe", "South Africa", 230);
INSERT INTO Boundaries VALUES("Zimbabwe", "Zambia", 763);
