INSERT INTO Languages VALUES(0, "Dari", "Afghanistan", 50);
INSERT INTO Languages VALUES(1, "Pashto", "Afghanistan", 35);
INSERT INTO Languages(id, name, country) VALUES(2, "English", "Akrot");
INSERT INTO Languages(id, name, country) VALUES(3, "Greek", "Akrot");
INSERT INTO Languages VALUES(4, "Albanian", "Albania", 98.8);
INSERT INTO Languages VALUES(5, "Greek", "Albania", 0.5);
INSERT INTO Languages(id, name, country) VALUES(6, "Arabic", "Algeria");
INSERT INTO Languages(id, name, country) VALUES(7, "French", "Algeria");
INSERT INTO Languages(id, name, country) VALUES(8, "Chaouia Berber", "Algeria");
INSERT INTO Languages(id, name, country) VALUES(9, "Mzab Berber", "Algeria");
INSERT INTO Languages(id, name, country) VALUES(10, "Tuareg Berber", "Algeria");
INSERT INTO Languages VALUES(11, "Samoan", "American Samoa", 90.6);
INSERT INTO Languages VALUES(12, "English", "American Samoa", 2.9);
INSERT INTO Languages VALUES(13, "Tongan", "American Samoa", 2.4);
INSERT INTO Languages(id, name, country) VALUES(14, "Catalan", "Andorra");
INSERT INTO Languages(id, name, country) VALUES(15, "French", "Andorra");
INSERT INTO Languages(id, name, country) VALUES(16, "Castilian", "Andorra");
INSERT INTO Languages(id, name, country) VALUES(17, "Portuguese", "Andorra");
INSERT INTO Languages(id, name, country) VALUES(18, "Portuguese", "Angola");
INSERT INTO Languages(id, name, country) VALUES(19, "English", "Anguilla");
INSERT INTO Languages(id, name, country) VALUES(20, "English", "Antigua and Barbuda");
INSERT INTO Languages(id, name, country) VALUES(21, "Spanish", "Argentina");
INSERT INTO Languages(id, name, country) VALUES(22, "Italian", "Argentina");
INSERT INTO Languages(id, name, country) VALUES(23, "English", "Argentina");
INSERT INTO Languages(id, name, country) VALUES(24, "German", "Argentina");
INSERT INTO Languages(id, name, country) VALUES(25, "French", "Argentina");
INSERT INTO Languages VALUES(26, "Armenian", "Armenia", 97.9);
INSERT INTO Languages VALUES(27, "Kurdish", "Armenia", 1);
INSERT INTO Languages VALUES(28, "Papiamento", "Aruba", 69.4);
INSERT INTO Languages VALUES(29, "Spanish", "Aruba", 13.7);
INSERT INTO Languages VALUES(30, "English", "Aruba", 7.1);
INSERT INTO Languages VALUES(31, "Dutch", "Aruba", 6.1);
INSERT INTO Languages VALUES(32, "Chinese", "Aruba", 1.5);
INSERT INTO Languages VALUES(33, "English", "Australia", 76.8);
INSERT INTO Languages VALUES(34, "Mandarin", "Australia", 1.6);
INSERT INTO Languages VALUES(35, "Italian", "Australia", 1.4);
INSERT INTO Languages VALUES(36, "Arabic", "Australia", 1.3);
INSERT INTO Languages VALUES(37, "Greek", "Australia", 1.2);
INSERT INTO Languages VALUES(38, "Cantonese", "Australia", 1.2);
INSERT INTO Languages VALUES(39, "Vietnamese", "Australia", 1.1);
INSERT INTO Languages VALUES(40, "German", "Austria", 88.6);
INSERT INTO Languages VALUES(41, "Turkish", "Austria", 2.3);
INSERT INTO Languages VALUES(42, "Serbian", "Austria", 2.2);
INSERT INTO Languages VALUES(43, "Croatian", "Austria", 1.6);
INSERT INTO Languages VALUES(44, "Azerbaijani", "Azerbaijan", 92.5);
INSERT INTO Languages VALUES(45, "Russian", "Azerbaijan", 1.4);
INSERT INTO Languages VALUES(46, "Armenian", "Azerbaijan", 1.4);
INSERT INTO Languages(id, name, country) VALUES(47, "English", "Bahamas, The");
INSERT INTO Languages(id, name, country) VALUES(48, "Creole", "Bahamas, The");
INSERT INTO Languages(id, name, country) VALUES(49, "Arabic", "Bahrain");
INSERT INTO Languages(id, name, country) VALUES(50, "English", "Bahrain");
INSERT INTO Languages(id, name, country) VALUES(51, "Farsi", "Bahrain");
INSERT INTO Languages(id, name, country) VALUES(52, "Urdu", "Bahrain");
INSERT INTO Languages(id, name, country) VALUES(53, "Bangla", "Bangladesh");
INSERT INTO Languages(id, name, country) VALUES(54, "English", "Bangladesh");
INSERT INTO Languages(id, name, country) VALUES(55, "English", "Barbados");
INSERT INTO Languages(id, name, country) VALUES(56, "Bajan", "Barbados");
INSERT INTO Languages VALUES(57, "Belarusian", "Belarus", 23.4);
INSERT INTO Languages VALUES(58, "Russian", "Belarus", 70.2);
INSERT INTO Languages VALUES(59, "Dutch", "Belgium", 60);
INSERT INTO Languages VALUES(60, "French", "Belgium", 40);
INSERT INTO Languages VALUES(61, "Spanish", "Belize", 46);
INSERT INTO Languages VALUES(62, "Creole", "Belize", 32.9);
INSERT INTO Languages VALUES(63, "English", "Belize", 3.9);
INSERT INTO Languages VALUES(64, "Garifuna", "Belize", 3.4);
INSERT INTO Languages VALUES(65, "German", "Belize", 3.3);
INSERT INTO Languages(id, name, country) VALUES(66, "French", "Benin");
INSERT INTO Languages(id, name, country) VALUES(67, "English", "Bermuda");
INSERT INTO Languages(id, name, country) VALUES(68, "Portuguese", "Bermuda");
INSERT INTO Languages VALUES(69, "Sharchhopka", "Bhutan", 28);
INSERT INTO Languages VALUES(70, "Dzongkha", "Bhutan", 24);
INSERT INTO Languages VALUES(71, "Lhotshamkha", "Bhutan", 22);
INSERT INTO Languages VALUES(72, "Spanish", "Bolivia", 60.7);
INSERT INTO Languages VALUES(73, "Quechua", "Bolivia", 21.2);
INSERT INTO Languages VALUES(74, "Aymara", "Bolivia", 14.6);
INSERT INTO Languages(id, name, country) VALUES(75, "Guarani", "Bolivia");
INSERT INTO Languages(id, name, country) VALUES(76, "Bosnian", "Bosnia and Herzegovina");
INSERT INTO Languages(id, name, country) VALUES(77, "Croatian", "Bosnia and Herzegovina");
INSERT INTO Languages(id, name, country) VALUES(78, "Serbian", "Bosnia and Herzegovina");
INSERT INTO Languages VALUES(79, "Setswana", "Botswana", 78.2);
INSERT INTO Languages VALUES(80, "Kalanga", "Botswana", 7.9);
INSERT INTO Languages VALUES(81, "Sekgalagadi", "Botswana", 2.8);
INSERT INTO Languages VALUES(82, "English", "Botswana", 2.1);
INSERT INTO Languages(id, name, country) VALUES(83, "Portuguese", "Brazil");
INSERT INTO Languages(id, name, country) VALUES(84, "English", "British Virgin Islands");
INSERT INTO Languages(id, name, country) VALUES(85, "Malay", "Brunei");
INSERT INTO Languages(id, name, country) VALUES(86, "English", "Brunei");
INSERT INTO Languages(id, name, country) VALUES(87, "Chinese", "Brunei");
INSERT INTO Languages VALUES(88, "Bulgarian", "Bulgaria", 76.8);
INSERT INTO Languages VALUES(89, "Turkish", "Bulgaria", 8.2);
INSERT INTO Languages VALUES(90, "Roma", "Bulgaria", 3.8);
INSERT INTO Languages(id, name, country) VALUES(91, "French", "Burkina Faso");
INSERT INTO Languages(id, name, country) VALUES(92, "Burmese", "Burma");
INSERT INTO Languages VALUES(93, "Kirundi", "Burundi", 29.7);
INSERT INTO Languages(id, name, country) VALUES(94, "Portuguese", "Cabo Verde");
INSERT INTO Languages(id, name, country) VALUES(95, "Crioulo", "Cabo Verde");
INSERT INTO Languages VALUES(96, "Khmer", "Cambodia", 96.3);
INSERT INTO Languages(id, name, country) VALUES(97, "English", "Cameroon");
INSERT INTO Languages(id, name, country) VALUES(98, "French", "Cameroon");
INSERT INTO Languages VALUES(99, "English", "Canada", 58.7);
INSERT INTO Languages VALUES(100, "French", "Canada", 22);
INSERT INTO Languages VALUES(101, "Punjabi", "Canada", 1.4);
INSERT INTO Languages VALUES(102, "Italian", "Canada", 1.3);
INSERT INTO Languages VALUES(103, "Spanish", "Canada", 1.3);
INSERT INTO Languages VALUES(104, "German", "Canada", 1.3);
INSERT INTO Languages VALUES(105, "Cantonese", "Canada", 1.2);
INSERT INTO Languages VALUES(106, "Tagalog", "Canada", 1.2);
INSERT INTO Languages VALUES(107, "Arabic", "Canada", 1.1);
INSERT INTO Languages VALUES(108, "English", "Cayman Islands", 90.9);
INSERT INTO Languages VALUES(109, "Spanish", "Cayman Islands", 4);
INSERT INTO Languages VALUES(110, "Filipino", "Cayman Islands", 3.3);
INSERT INTO Languages(id, name, country) VALUES(111, "French", "Central African Republic");
INSERT INTO Languages(id, name, country) VALUES(112, "Sangho", "Central African Republic");
INSERT INTO Languages(id, name, country) VALUES(113, "French", "Chad");
INSERT INTO Languages(id, name, country) VALUES(114, "Arabic", "Chad");
INSERT INTO Languages(id, name, country) VALUES(115, "Sara", "Chad");
INSERT INTO Languages VALUES(116, "Spanish", "Chile", 99.5);
INSERT INTO Languages VALUES(117, "English", "Chile", 10.2);
INSERT INTO Languages(id, name, country) VALUES(118, "Yue", "China");
INSERT INTO Languages(id, name, country) VALUES(119, "Wu", "China");
INSERT INTO Languages(id, name, country) VALUES(120, "Minbei", "China");
INSERT INTO Languages(id, name, country) VALUES(121, "Minnan", "China");
INSERT INTO Languages(id, name, country) VALUES(122, "Xiang", "China");
INSERT INTO Languages(id, name, country) VALUES(123, "Gan", "China");
INSERT INTO Languages(id, name, country) VALUES(124, "English", "Christmas Island");
INSERT INTO Languages(id, name, country) VALUES(125, "Chinese", "Christmas Island");
INSERT INTO Languages(id, name, country) VALUES(126, "Malay", "Christmas Island");
INSERT INTO Languages(id, name, country) VALUES(127, "Malay", "Cocos Islands");
INSERT INTO Languages(id, name, country) VALUES(128, "English", "Cocos Islands");
INSERT INTO Languages(id, name, country) VALUES(129, "Spanish", "Colombia");
INSERT INTO Languages(id, name, country) VALUES(130, "Arabic", "Comoros");
INSERT INTO Languages(id, name, country) VALUES(131, "French", "Comoros");
INSERT INTO Languages(id, name, country) VALUES(132, "Shikomoro", "Comoros");
INSERT INTO Languages(id, name, country) VALUES(133, "French", "Congo, Democratic Republic of the");
INSERT INTO Languages(id, name, country) VALUES(134, "Lingala", "Congo, Democratic Republic of the");
INSERT INTO Languages(id, name, country) VALUES(135, "Kingwana", "Congo, Democratic Republic of the");
INSERT INTO Languages(id, name, country) VALUES(136, "Kikongo", "Congo, Democratic Republic of the");
INSERT INTO Languages(id, name, country) VALUES(137, "Tshiluba", "Congo, Democratic Republic of the");
INSERT INTO Languages(id, name, country) VALUES(138, "French", "Congo, Republic of the");
INSERT INTO Languages VALUES(139, "English", "Cook Islands", 86.4);
INSERT INTO Languages VALUES(140, "Cook Islands Maori", "Cook Islands", 76.2);
INSERT INTO Languages(id, name, country) VALUES(141, "Spanish", "Costa Rica");
INSERT INTO Languages(id, name, country) VALUES(142, "English", "Costa Rica");
INSERT INTO Languages(id, name, country) VALUES(143, "French", "Cote d'Ivoire");
INSERT INTO Languages VALUES(144, "Croatian", "Croatia", 95.6);
INSERT INTO Languages VALUES(145, "Serbian", "Croatia", 1.2);
INSERT INTO Languages(id, name, country) VALUES(146, "Spanish", "Cuba");
INSERT INTO Languages VALUES(147, "Papiamentu", "Curacao", 81.2);
INSERT INTO Languages VALUES(148, "Dutch", "Curacao", 8);
INSERT INTO Languages VALUES(149, "Spanish", "Curacao", 4);
INSERT INTO Languages VALUES(150, "English", "Curacao", 2.9);
INSERT INTO Languages VALUES(151, "Greek", "Cyprus", 80.9);
INSERT INTO Languages VALUES(152, "Turkish", "Cyprus", 0.2);
INSERT INTO Languages VALUES(153, "English", "Cyprus", 4.1);
INSERT INTO Languages VALUES(154, "Romanian", "Cyprus", 2.9);
INSERT INTO Languages VALUES(155, "Russian", "Cyprus", 2.5);
INSERT INTO Languages VALUES(156, "Bulgarian", "Cyprus", 2.2);
INSERT INTO Languages VALUES(157, "Arabic", "Cyprus", 1.2);
INSERT INTO Languages VALUES(158, "Filippino", "Cyprus", 1.1);
INSERT INTO Languages VALUES(159, "Czech", "Czech Republic", 95.4);
INSERT INTO Languages VALUES(160, "Slovak", "Czech Republic", 1.6);
INSERT INTO Languages(id, name, country) VALUES(161, "Danish", "Denmark");
INSERT INTO Languages(id, name, country) VALUES(162, "Faroese", "Denmark");
INSERT INTO Languages(id, name, country) VALUES(163, "Greenlandic", "Denmark");
INSERT INTO Languages(id, name, country) VALUES(164, "German", "Denmark");
INSERT INTO Languages(id, name, country) VALUES(165, "English", "Dhekelia");
INSERT INTO Languages(id, name, country) VALUES(166, "Greek", "Dhekelia");
INSERT INTO Languages(id, name, country) VALUES(167, "French", "Djibouti");
INSERT INTO Languages(id, name, country) VALUES(168, "Arabic", "Djibouti");
INSERT INTO Languages(id, name, country) VALUES(169, "Somali", "Djibouti");
INSERT INTO Languages(id, name, country) VALUES(170, "Afar", "Djibouti");
INSERT INTO Languages(id, name, country) VALUES(171, "English", "Dominica");
INSERT INTO Languages(id, name, country) VALUES(172, "Spanish", "Dominican Republic");
INSERT INTO Languages VALUES(173, "Spanish", "Ecuador", 93);
INSERT INTO Languages VALUES(174, "Quechua", "Ecuador", 4.1);
INSERT INTO Languages(id, name, country) VALUES(175, "Arabic", "Egypt");
INSERT INTO Languages(id, name, country) VALUES(176, "Spanish", "El Salvador");
INSERT INTO Languages(id, name, country) VALUES(177, "Nahua", "El Salvador");
INSERT INTO Languages VALUES(178, "Spanish", "Equatorial Guinea", 67.6);
INSERT INTO Languages(id, name, country) VALUES(179, "Fang", "Equatorial Guinea");
INSERT INTO Languages VALUES(180, "Bubi)", "Equatorial Guinea", 32.4);
INSERT INTO Languages(id, name, country) VALUES(181, "Tigrinya", "Eritrea");
INSERT INTO Languages(id, name, country) VALUES(182, "Arabic", "Eritrea");
INSERT INTO Languages(id, name, country) VALUES(183, "English", "Eritrea");
INSERT INTO Languages(id, name, country) VALUES(184, "Tigre", "Eritrea");
INSERT INTO Languages(id, name, country) VALUES(185, "Kunama", "Eritrea");
INSERT INTO Languages(id, name, country) VALUES(186, "Afar", "Eritrea");
INSERT INTO Languages VALUES(187, "Estonian", "Estonia", 68.5);
INSERT INTO Languages VALUES(188, "Russian", "Estonia", 29.6);
INSERT INTO Languages VALUES(189, "Ukrainian", "Estonia", 0.6);
INSERT INTO Languages VALUES(190, "Oromo", "Ethiopia", 33.8);
INSERT INTO Languages VALUES(191, "Amharic", "Ethiopia", 29.3);
INSERT INTO Languages VALUES(192, "Somali", "Ethiopia", 6.2);
INSERT INTO Languages VALUES(193, "Tigrigna", "Ethiopia", 5.9);
INSERT INTO Languages VALUES(194, "Sidamo", "Ethiopia", 4);
INSERT INTO Languages VALUES(195, "Wolaytta", "Ethiopia", 2.2);
INSERT INTO Languages VALUES(196, "Gurage", "Ethiopia", 2);
INSERT INTO Languages VALUES(197, "Afar", "Ethiopia", 1.7);
INSERT INTO Languages VALUES(198, "Hadiyya", "Ethiopia", 1.7);
INSERT INTO Languages VALUES(199, "Gamo", "Ethiopia", 1.5);
INSERT INTO Languages VALUES(200, "Gedeo", "Ethiopia", 1.3);
INSERT INTO Languages VALUES(201, "Opuuo", "Ethiopia", 1.2);
INSERT INTO Languages VALUES(202, "Kafa", "Ethiopia", 1.1);
INSERT INTO Languages(id, name, country) VALUES(203, "English", "Ethiopia");
INSERT INTO Languages(id, name, country) VALUES(204, "Arabic", "Ethiopia");
INSERT INTO Languages VALUES(205, "English", "Falkland Islands", 89);
INSERT INTO Languages VALUES(206, "Spanish", "Falkland Islands", 7.7);
INSERT INTO Languages(id, name, country) VALUES(207, "Faroese", "Faroe Islands");
INSERT INTO Languages(id, name, country) VALUES(208, "Danish", "Faroe Islands");
INSERT INTO Languages(id, name, country) VALUES(209, "English", "Fiji");
INSERT INTO Languages(id, name, country) VALUES(210, "Fijian", "Fiji");
INSERT INTO Languages(id, name, country) VALUES(211, "Hindustani", "Fiji");
INSERT INTO Languages VALUES(212, "Finnish", "Finland", 94.2);
INSERT INTO Languages VALUES(213, "Swedish", "Finland", 5.5);
INSERT INTO Languages VALUES(214, "French", "France", 100);
INSERT INTO Languages VALUES(215, "French", "French Polynesia", 61.1);
INSERT INTO Languages VALUES(216, "Polynesian", "French Polynesia", 31.4);
INSERT INTO Languages(id, name, country) VALUES(217, "French", "Gabon");
INSERT INTO Languages(id, name, country) VALUES(218, "Fang", "Gabon");
INSERT INTO Languages(id, name, country) VALUES(219, "Myene", "Gabon");
INSERT INTO Languages(id, name, country) VALUES(220, "Nzebi", "Gabon");
INSERT INTO Languages(id, name, country) VALUES(221, "Bapounou/Eschira", "Gabon");
INSERT INTO Languages(id, name, country) VALUES(222, "Bandjabi", "Gabon");
INSERT INTO Languages(id, name, country) VALUES(223, "English", "Gambia, The");
INSERT INTO Languages(id, name, country) VALUES(224, "Mandinka", "Gambia, The");
INSERT INTO Languages(id, name, country) VALUES(225, "Wolof", "Gambia, The");
INSERT INTO Languages(id, name, country) VALUES(226, "Fula", "Gambia, The");
INSERT INTO Languages(id, name, country) VALUES(227, "Arabic", "Gaza Strip");
INSERT INTO Languages(id, name, country) VALUES(228, "Hebrew", "Gaza Strip");
INSERT INTO Languages(id, name, country) VALUES(229, "English", "Gaza Strip");
INSERT INTO Languages VALUES(230, "Georgian", "Georgia", 71);
INSERT INTO Languages VALUES(231, "Russian", "Georgia", 9);
INSERT INTO Languages VALUES(232, "Armenian", "Georgia", 7);
INSERT INTO Languages VALUES(233, "Azeri", "Georgia", 6);
INSERT INTO Languages(id, name, country) VALUES(234, "German", "Germany");
INSERT INTO Languages VALUES(235, "Asante", "Ghana", 14.8);
INSERT INTO Languages VALUES(236, "Ewe", "Ghana", 12.7);
INSERT INTO Languages VALUES(237, "Fante", "Ghana", 9.9);
INSERT INTO Languages VALUES(238, "Boron", "Ghana", 4.6);
INSERT INTO Languages VALUES(239, "Dagomba", "Ghana", 4.3);
INSERT INTO Languages VALUES(240, "Dangme", "Ghana", 4.3);
INSERT INTO Languages VALUES(241, "Dagarte", "Ghana", 3.7);
INSERT INTO Languages VALUES(242, "Akyem", "Ghana", 3.4);
INSERT INTO Languages VALUES(243, "Ga", "Ghana", 3.4);
INSERT INTO Languages VALUES(244, "Akuapem", "Ghana", 2.9);
INSERT INTO Languages(id, name, country) VALUES(245, "English", "Gibraltar");
INSERT INTO Languages(id, name, country) VALUES(246, "Spanish", "Gibraltar");
INSERT INTO Languages(id, name, country) VALUES(247, "Italian", "Gibraltar");
INSERT INTO Languages(id, name, country) VALUES(248, "Portuguese", "Gibraltar");
INSERT INTO Languages VALUES(249, "Greek", "Greece", 99);
INSERT INTO Languages(id, name, country) VALUES(250, "Greenlandic", "Greenland");
INSERT INTO Languages(id, name, country) VALUES(251, "Danish", "Greenland");
INSERT INTO Languages(id, name, country) VALUES(252, "English", "Greenland");
INSERT INTO Languages(id, name, country) VALUES(253, "English", "Grenada");
INSERT INTO Languages VALUES(254, "English", "Guam", 43.6);
INSERT INTO Languages VALUES(255, "Filipino", "Guam", 21.2);
INSERT INTO Languages VALUES(256, "Chamorro", "Guam", 17.8);
INSERT INTO Languages VALUES(257, "Spanish", "Guatemala", 60);
INSERT INTO Languages(id, name, country) VALUES(258, "English", "Guernsey");
INSERT INTO Languages(id, name, country) VALUES(259, "French", "Guernsey");
INSERT INTO Languages(id, name, country) VALUES(260, "French", "Guinea");
INSERT INTO Languages(id, name, country) VALUES(261, "Portuguese", "Guinea-Bissau");
INSERT INTO Languages(id, name, country) VALUES(262, "Crioulo", "Guinea-Bissau");
INSERT INTO Languages(id, name, country) VALUES(263, "English", "Guyana");
INSERT INTO Languages(id, name, country) VALUES(264, "Creole", "Guyana");
INSERT INTO Languages(id, name, country) VALUES(265, "Caribbean Hindustani", "Guyana");
INSERT INTO Languages(id, name, country) VALUES(266, "Urdu", "Guyana");
INSERT INTO Languages(id, name, country) VALUES(267, "French", "Haiti");
INSERT INTO Languages(id, name, country) VALUES(268, "Creole", "Haiti");
INSERT INTO Languages(id, name, country) VALUES(269, "Italian", "Holy See");
INSERT INTO Languages(id, name, country) VALUES(270, "Latin", "Holy See");
INSERT INTO Languages(id, name, country) VALUES(271, "French", "Holy See");
INSERT INTO Languages(id, name, country) VALUES(272, "Spanish", "Honduras");
INSERT INTO Languages VALUES(273, "Cantonese", "Hong Kong", 89.5);
INSERT INTO Languages VALUES(274, "English", "Hong Kong", 3.5);
INSERT INTO Languages VALUES(275, "Putonghua", "Hong Kong", 1.4);
INSERT INTO Languages VALUES(276, "Hungarian", "Hungary", 99.6);
INSERT INTO Languages VALUES(277, "English", "Hungary", 16);
INSERT INTO Languages VALUES(278, "German", "Hungary", 11.2);
INSERT INTO Languages VALUES(279, "Russian", "Hungary", 1.6);
INSERT INTO Languages VALUES(280, "Romanian", "Hungary", 1.3);
INSERT INTO Languages VALUES(281, "French", "Hungary", 1.2);
INSERT INTO Languages(id, name, country) VALUES(282, "Icelandic", "Iceland");
INSERT INTO Languages(id, name, country) VALUES(283, "English", "Iceland");
INSERT INTO Languages VALUES(284, "Hindi", "India", 41);
INSERT INTO Languages VALUES(285, "Bengali", "India", 8.1);
INSERT INTO Languages VALUES(286, "Telugu", "India", 7.2);
INSERT INTO Languages VALUES(287, "Marathi", "India", 7);
INSERT INTO Languages VALUES(288, "Tamil", "India", 5.9);
INSERT INTO Languages VALUES(289, "Urdu", "India", 5);
INSERT INTO Languages VALUES(290, "Gujarati", "India", 4.5);
INSERT INTO Languages VALUES(291, "Kannada", "India", 3.7);
INSERT INTO Languages VALUES(292, "Malayalam", "India", 3.2);
INSERT INTO Languages VALUES(293, "Oriya", "India", 3.2);
INSERT INTO Languages VALUES(294, "Punjabi", "India", 2.8);
INSERT INTO Languages VALUES(295, "Assamese", "India", 1.3);
INSERT INTO Languages VALUES(296, "Maithili", "India", 1.2);
INSERT INTO Languages(id, name, country) VALUES(297, "Bahasa Indonesia", "Indonesia");
INSERT INTO Languages(id, name, country) VALUES(298, "English", "Indonesia");
INSERT INTO Languages(id, name, country) VALUES(299, "Dutch", "Indonesia");
INSERT INTO Languages VALUES(300, "Persian", "Iran", 53);
INSERT INTO Languages VALUES(301, "Kurdish", "Iran", 10);
INSERT INTO Languages VALUES(302, "Luri", "Iran", 6);
INSERT INTO Languages VALUES(303, "Balochi", "Iran", 2);
INSERT INTO Languages VALUES(304, "Arabic", "Iran", 2);
INSERT INTO Languages(id, name, country) VALUES(305, "Arabic", "Iraq");
INSERT INTO Languages(id, name, country) VALUES(306, "Kurdish", "Iraq");
INSERT INTO Languages(id, name, country) VALUES(307, "Turkmen", "Iraq");
INSERT INTO Languages(id, name, country) VALUES(308, "Assyrian", "Iraq");
INSERT INTO Languages(id, name, country) VALUES(309, "Armenian", "Iraq");
INSERT INTO Languages(id, name, country) VALUES(310, "English", "Ireland");
INSERT INTO Languages(id, name, country) VALUES(311, "Irish", "Ireland");
INSERT INTO Languages(id, name, country) VALUES(312, "English", "Isle of Man");
INSERT INTO Languages(id, name, country) VALUES(313, "Manx Gaelic", "Isle of Man");
INSERT INTO Languages(id, name, country) VALUES(314, "Hebrew", "Israel");
INSERT INTO Languages(id, name, country) VALUES(315, "Arabic", "Israel");
INSERT INTO Languages(id, name, country) VALUES(316, "English", "Israel");
INSERT INTO Languages(id, name, country) VALUES(317, "Italian", "Italy");
INSERT INTO Languages(id, name, country) VALUES(318, "German", "Italy");
INSERT INTO Languages(id, name, country) VALUES(319, "French", "Italy");
INSERT INTO Languages(id, name, country) VALUES(320, "Slovene", "Italy");
INSERT INTO Languages(id, name, country) VALUES(321, "English", "Jamaica");
INSERT INTO Languages(id, name, country) VALUES(322, "Japanese", "Japan");
INSERT INTO Languages VALUES(323, "English", "Jersey", 94.5);
INSERT INTO Languages VALUES(324, "Portuguese", "Jersey", 4.6);
INSERT INTO Languages(id, name, country) VALUES(325, "Arabic", "Jordan");
INSERT INTO Languages(id, name, country) VALUES(326, "English", "Jordan");
INSERT INTO Languages VALUES(327, "Kazakh", "Kazakhstan", 64.4);
INSERT INTO Languages VALUES(328, "Russian", "Kazakhstan", 95);
INSERT INTO Languages(id, name, country) VALUES(329, "English", "Kenya");
INSERT INTO Languages(id, name, country) VALUES(330, "Kiswahili", "Kenya");
INSERT INTO Languages(id, name, country) VALUES(331, "I-Kiribati", "Kiribati");
INSERT INTO Languages(id, name, country) VALUES(332, "English", "Kiribati");
INSERT INTO Languages(id, name, country) VALUES(333, "Korean", "Korea, North");
INSERT INTO Languages(id, name, country) VALUES(334, "Korean", "Korea, South");
INSERT INTO Languages(id, name, country) VALUES(335, "English", "Korea, South");
INSERT INTO Languages(id, name, country) VALUES(336, "Albanian", "Kosovo");
INSERT INTO Languages(id, name, country) VALUES(337, "Serbian", "Kosovo");
INSERT INTO Languages(id, name, country) VALUES(338, "Bosnian", "Kosovo");
INSERT INTO Languages(id, name, country) VALUES(339, "Turkish", "Kosovo");
INSERT INTO Languages(id, name, country) VALUES(340, "Roma", "Kosovo");
INSERT INTO Languages(id, name, country) VALUES(341, "Arabic", "Kuwait");
INSERT INTO Languages VALUES(342, "Kyrgyz", "Kyrgyzstan", 64.7);
INSERT INTO Languages VALUES(343, "Uzbek", "Kyrgyzstan", 13.6);
INSERT INTO Languages VALUES(344, "Russian", "Kyrgyzstan", 12.5);
INSERT INTO Languages VALUES(345, "Dungun", "Kyrgyzstan", 1);
INSERT INTO Languages(id, name, country) VALUES(346, "Lao", "Laos");
INSERT INTO Languages(id, name, country) VALUES(347, "French", "Laos");
INSERT INTO Languages(id, name, country) VALUES(348, "English", "Laos");
INSERT INTO Languages VALUES(349, "Latvian", "Latvia", 56.3);
INSERT INTO Languages VALUES(350, "Russian", "Latvia", 33.8);
INSERT INTO Languages(id, name, country) VALUES(351, "Arabic", "Lebanon");
INSERT INTO Languages(id, name, country) VALUES(352, "French", "Lebanon");
INSERT INTO Languages(id, name, country) VALUES(353, "English", "Lebanon");
INSERT INTO Languages(id, name, country) VALUES(354, "Armenian", "Lebanon");
INSERT INTO Languages(id, name, country) VALUES(355, "Sesotho", "Lesotho");
INSERT INTO Languages(id, name, country) VALUES(356, "English", "Lesotho");
INSERT INTO Languages(id, name, country) VALUES(357, "Zulu", "Lesotho");
INSERT INTO Languages(id, name, country) VALUES(358, "Xhosa", "Lesotho");
INSERT INTO Languages VALUES(359, "English", "Liberia", 20);
INSERT INTO Languages(id, name, country) VALUES(360, "Arabic", "Libya");
INSERT INTO Languages(id, name, country) VALUES(361, "Italian", "Libya");
INSERT INTO Languages(id, name, country) VALUES(362, "English Berber", "Libya");
INSERT INTO Languages VALUES(363, "German", "Liechtenstein", 94.5);
INSERT INTO Languages VALUES(364, "Italian", "Liechtenstein", 1.1);
INSERT INTO Languages VALUES(365, "Lithuanian", "Lithuania", 82);
INSERT INTO Languages VALUES(366, "Russian", "Lithuania", 8);
INSERT INTO Languages VALUES(367, "Polish", "Lithuania", 5.6);
INSERT INTO Languages(id, name, country) VALUES(368, "Luxembourgish", "Luxembourg");
INSERT INTO Languages(id, name, country) VALUES(369, "French", "Luxembourg");
INSERT INTO Languages(id, name, country) VALUES(370, "German", "Luxembourg");
INSERT INTO Languages VALUES(371, "Cantonese", "Macau", 83.3);
INSERT INTO Languages VALUES(372, "Mandarin", "Macau", 5);
INSERT INTO Languages VALUES(373, "Hokkien", "Macau", 3.7);
INSERT INTO Languages VALUES(374, "English", "Macau", 2.3);
INSERT INTO Languages VALUES(375, "Tagalog", "Macau", 1.7);
INSERT INTO Languages VALUES(376, "Portuguese", "Macau", 0.7);
INSERT INTO Languages VALUES(377, "Macedonian", "Macedonia", 66.5);
INSERT INTO Languages VALUES(378, "Albanian", "Macedonia", 25.1);
INSERT INTO Languages VALUES(379, "Turkish", "Macedonia", 3.5);
INSERT INTO Languages VALUES(380, "Roma", "Macedonia", 1.9);
INSERT INTO Languages VALUES(381, "Serbian", "Macedonia", 1.2);
INSERT INTO Languages(id, name, country) VALUES(382, "French", "Madagascar");
INSERT INTO Languages(id, name, country) VALUES(383, "Malagasy", "Madagascar");
INSERT INTO Languages(id, name, country) VALUES(384, "English", "Madagascar");
INSERT INTO Languages(id, name, country) VALUES(385, "English", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(386, "Chichewa", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(387, "Chinyanja", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(388, "Chiyao", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(389, "Chitumbuka", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(390, "Chilomwe", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(391, "Chinkhonde", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(392, "Chingoni", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(393, "Chisena", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(394, "Chitonga", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(395, "Chinyakyusa", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(396, "Chilambya", "Malawi");
INSERT INTO Languages(id, name, country) VALUES(397, "Bahasa Malaysia", "Malaysia");
INSERT INTO Languages(id, name, country) VALUES(398, "English", "Malaysia");
INSERT INTO Languages(id, name, country) VALUES(399, "Chinese", "Malaysia");
INSERT INTO Languages(id, name, country) VALUES(400, "Tamil", "Malaysia");
INSERT INTO Languages(id, name, country) VALUES(401, "Telugu", "Malaysia");
INSERT INTO Languages(id, name, country) VALUES(402, "Malayalam", "Malaysia");
INSERT INTO Languages(id, name, country) VALUES(403, "Panjabi", "Malaysia");
INSERT INTO Languages(id, name, country) VALUES(404, "Thai", "Malaysia");
INSERT INTO Languages(id, name, country) VALUES(405, "Dhivehi", "Maldives");
INSERT INTO Languages(id, name, country) VALUES(406, "English", "Maldives");
INSERT INTO Languages(id, name, country) VALUES(407, "French", "Mali");
INSERT INTO Languages VALUES(408, "Bambara", "Mali", 46.3);
INSERT INTO Languages VALUES(409, "Peul/foulfoulbe", "Mali", 9.4);
INSERT INTO Languages VALUES(410, "Dogon", "Mali", 7.2);
INSERT INTO Languages VALUES(411, "Maraka/soninke", "Mali", 6.4);
INSERT INTO Languages VALUES(412, "Malinke", "Mali", 5.6);
INSERT INTO Languages VALUES(413, "Sonrhai/djerma", "Mali", 5.6);
INSERT INTO Languages VALUES(414, "Minianka", "Mali", 4.3);
INSERT INTO Languages VALUES(415, "Tamacheq", "Mali", 3.5);
INSERT INTO Languages VALUES(416, "Senoufo", "Mali", 2.6);
INSERT INTO Languages VALUES(417, "Maltese", "Malta", 90.1);
INSERT INTO Languages VALUES(418, "English", "Malta", 6);
INSERT INTO Languages VALUES(419, "Marshallese", "Marshall Islands", 98.2);
INSERT INTO Languages(id, name, country) VALUES(420, "Arabic", "Mauritania");
INSERT INTO Languages(id, name, country) VALUES(421, "Pulaar", "Mauritania");
INSERT INTO Languages(id, name, country) VALUES(422, "Soninke", "Mauritania");
INSERT INTO Languages(id, name, country) VALUES(423, "Wolof", "Mauritania");
INSERT INTO Languages(id, name, country) VALUES(424, "French", "Mauritania");
INSERT INTO Languages(id, name, country) VALUES(425, "Hassaniya", "Mauritania");
INSERT INTO Languages VALUES(426, "Creole", "Mauritius", 86.5);
INSERT INTO Languages VALUES(427, "Bhojpuri", "Mauritius", 5.3);
INSERT INTO Languages VALUES(428, "French", "Mauritius", 4.1);
INSERT INTO Languages(id, name, country) VALUES(429, "English", "Micronesia, Federated States of");
INSERT INTO Languages(id, name, country) VALUES(430, "Chuukese", "Micronesia, Federated States of");
INSERT INTO Languages(id, name, country) VALUES(431, "Kosrean", "Micronesia, Federated States of");
INSERT INTO Languages(id, name, country) VALUES(432, "Pohnpeian", "Micronesia, Federated States of");
INSERT INTO Languages(id, name, country) VALUES(433, "Yapese", "Micronesia, Federated States of");
INSERT INTO Languages(id, name, country) VALUES(434, "Ulithian", "Micronesia, Federated States of");
INSERT INTO Languages(id, name, country) VALUES(435, "Woleaian", "Micronesia, Federated States of");
INSERT INTO Languages(id, name, country) VALUES(436, "Nukuoro", "Micronesia, Federated States of");
INSERT INTO Languages(id, name, country) VALUES(437, "Kapingamarangi", "Micronesia, Federated States of");
INSERT INTO Languages VALUES(438, "Moldovan", "Moldova", 58.8);
INSERT INTO Languages VALUES(439, "Romanian", "Moldova", 16.4);
INSERT INTO Languages VALUES(440, "Russian", "Moldova", 16);
INSERT INTO Languages VALUES(441, "Ukrainian", "Moldova", 3.8);
INSERT INTO Languages VALUES(442, "Gagauz", "Moldova", 3.1);
INSERT INTO Languages VALUES(443, "Bulgarian", "Moldova", 1.1);
INSERT INTO Languages(id, name, country) VALUES(444, "French", "Monaco");
INSERT INTO Languages(id, name, country) VALUES(445, "English", "Monaco");
INSERT INTO Languages(id, name, country) VALUES(446, "Italian", "Monaco");
INSERT INTO Languages(id, name, country) VALUES(447, "Monegasque", "Monaco");
INSERT INTO Languages VALUES(448, "Khalkha Mongol", "Mongolia", 90);
INSERT INTO Languages(id, name, country) VALUES(449, "Turkic", "Mongolia");
INSERT INTO Languages(id, name, country) VALUES(450, "Russian", "Mongolia");
INSERT INTO Languages VALUES(451, "Serbian", "Montenegro", 42.9);
INSERT INTO Languages VALUES(452, "Montenegrin", "Montenegro", 37);
INSERT INTO Languages VALUES(453, "Bosnian", "Montenegro", 5.3);
INSERT INTO Languages VALUES(454, "Albanian", "Montenegro", 5.3);
INSERT INTO Languages VALUES(455, "Serbo-Croat", "Montenegro", 2);
INSERT INTO Languages(id, name, country) VALUES(456, "English", "Montserrat");
INSERT INTO Languages(id, name, country) VALUES(457, "Arabic", "Morocco");
INSERT INTO Languages(id, name, country) VALUES(458, "Tachelhit", "Morocco");
INSERT INTO Languages(id, name, country) VALUES(459, "Tarifit)", "Morocco");
INSERT INTO Languages(id, name, country) VALUES(460, "French", "Morocco");
INSERT INTO Languages VALUES(461, "Emakhuwa", "Mozambique", 25.3);
INSERT INTO Languages VALUES(462, "Portuguese", "Mozambique", 10.7);
INSERT INTO Languages VALUES(463, "Xichangana", "Mozambique", 10.3);
INSERT INTO Languages VALUES(464, "Cisena", "Mozambique", 7.5);
INSERT INTO Languages VALUES(465, "Elomwe", "Mozambique", 7);
INSERT INTO Languages VALUES(466, "Echuwabo", "Mozambique", 5.1);
INSERT INTO Languages VALUES(467, "Nama/Damara", "Namibia", 11.3);
INSERT INTO Languages VALUES(468, "Afrikaans", "Namibia", 10.4);
INSERT INTO Languages VALUES(469, "English", "Namibia", 3.4);
INSERT INTO Languages VALUES(470, "Nauruan", "Nauru", 93);
INSERT INTO Languages VALUES(471, "English", "Nauru", 2);
INSERT INTO Languages VALUES(472, "Nepali", "Nepal", 44.6);
INSERT INTO Languages VALUES(473, "Maithali", "Nepal", 11.7);
INSERT INTO Languages VALUES(474, "Bhojpuri", "Nepal", 6);
INSERT INTO Languages VALUES(475, "Tharu", "Nepal", 5.8);
INSERT INTO Languages VALUES(476, "Tamang", "Nepal", 5.1);
INSERT INTO Languages VALUES(477, "Newar", "Nepal", 3.2);
INSERT INTO Languages VALUES(478, "Magar", "Nepal", 3);
INSERT INTO Languages VALUES(479, "Bajjika", "Nepal", 3);
INSERT INTO Languages VALUES(480, "Urdu", "Nepal", 2.6);
INSERT INTO Languages VALUES(481, "Avadhi", "Nepal", 1.9);
INSERT INTO Languages VALUES(482, "Limbu", "Nepal", 1.3);
INSERT INTO Languages VALUES(483, "Gurung", "Nepal", 1.2);
INSERT INTO Languages(id, name, country) VALUES(484, "Dutch", "Netherlands");
INSERT INTO Languages(id, name, country) VALUES(485, "French", "New Caledonia");
INSERT INTO Languages VALUES(486, "English", "New Zealand", 89.8);
INSERT INTO Languages VALUES(487, "Maori", "New Zealand", 3.5);
INSERT INTO Languages VALUES(488, "Samoan", "New Zealand", 2);
INSERT INTO Languages VALUES(489, "Hindi", "New Zealand", 1.6);
INSERT INTO Languages VALUES(490, "French", "New Zealand", 1.2);
INSERT INTO Languages VALUES(491, "Northern Chinese", "New Zealand", 1.2);
INSERT INTO Languages VALUES(492, "Yue", "New Zealand", 1);
INSERT INTO Languages(id, name, country) VALUES(493, "New Zealand Sign Language", "New Zealand");
INSERT INTO Languages VALUES(494, "Spanish", "Nicaragua", 95.3);
INSERT INTO Languages VALUES(495, "Miskito", "Nicaragua", 2.2);
INSERT INTO Languages(id, name, country) VALUES(496, "French", "Niger");
INSERT INTO Languages(id, name, country) VALUES(497, "Hausa", "Niger");
INSERT INTO Languages(id, name, country) VALUES(498, "Djerma", "Niger");
INSERT INTO Languages(id, name, country) VALUES(499, "English", "Nigeria");
INSERT INTO Languages(id, name, country) VALUES(500, "Hausa", "Nigeria");
INSERT INTO Languages(id, name, country) VALUES(501, "Yoruba", "Nigeria");
INSERT INTO Languages(id, name, country) VALUES(502, "Igbo", "Nigeria");
INSERT INTO Languages(id, name, country) VALUES(503, "Fulani", "Nigeria");
INSERT INTO Languages VALUES(504, "Niuean", "Niue", 46);
INSERT INTO Languages VALUES(505, "English", "Niue", 11);
INSERT INTO Languages VALUES(506, "English", "Norfolk Island", 67.6);
INSERT INTO Languages VALUES(507, "Chamorro", "Northern Mariana Islands", 24.1);
INSERT INTO Languages VALUES(508, "English", "Northern Mariana Islands", 17);
INSERT INTO Languages VALUES(509, "Chinese", "Northern Mariana Islands", 6.8);
INSERT INTO Languages(id, name, country) VALUES(510, "Bokmal Norwegian", "Norway");
INSERT INTO Languages(id, name, country) VALUES(511, "Nynorsk Norwegian", "Norway");
INSERT INTO Languages(id, name, country) VALUES(512, "Arabic", "Oman");
INSERT INTO Languages(id, name, country) VALUES(513, "English", "Oman");
INSERT INTO Languages(id, name, country) VALUES(514, "Baluchi", "Oman");
INSERT INTO Languages(id, name, country) VALUES(515, "Urdu", "Oman");
INSERT INTO Languages VALUES(516, "Punjabi", "Pakistan", 48);
INSERT INTO Languages VALUES(517, "Sindhi", "Pakistan", 12);
INSERT INTO Languages VALUES(518, "Saraiki", "Pakistan", 10);
INSERT INTO Languages VALUES(519, "Pashto", "Pakistan", 8);
INSERT INTO Languages VALUES(520, "Urdu", "Pakistan", 8);
INSERT INTO Languages VALUES(521, "Balochi", "Pakistan", 3);
INSERT INTO Languages VALUES(522, "Hindko", "Pakistan", 2);
INSERT INTO Languages VALUES(523, "Brahui", "Pakistan", 1);
INSERT INTO Languages(id, name, country) VALUES(524, "English", "Pakistan");
INSERT INTO Languages(id, name, country) VALUES(525, "Burushaski", "Pakistan");
INSERT INTO Languages VALUES(526, "Palauan", "Palau", 66.6);
INSERT INTO Languages VALUES(527, "Carolinian", "Palau", 0.7);
INSERT INTO Languages VALUES(528, "English", "Palau", 15.5);
INSERT INTO Languages VALUES(529, "Filipino", "Palau", 10.8);
INSERT INTO Languages VALUES(530, "Chinese", "Palau", 1.8);
INSERT INTO Languages(id, name, country) VALUES(531, "Spanish", "Panama");
INSERT INTO Languages VALUES(532, "English", "Panama", 14);
INSERT INTO Languages(id, name, country) VALUES(533, "Tok Pisin", "Papua New Guinea");
INSERT INTO Languages(id, name, country) VALUES(534, "English", "Papua New Guinea");
INSERT INTO Languages(id, name, country) VALUES(535, "Hiri Motu", "Papua New Guinea");
INSERT INTO Languages(id, name, country) VALUES(536, "Spanish", "Paraguay");
INSERT INTO Languages(id, name, country) VALUES(537, "Guarani", "Paraguay");
INSERT INTO Languages VALUES(538, "Spanish", "Peru", 84.1);
INSERT INTO Languages VALUES(539, "Quechua", "Peru", 13);
INSERT INTO Languages VALUES(540, "Aymara", "Peru", 1.7);
INSERT INTO Languages VALUES(541, "Ashaninka", "Peru", 0.3);
INSERT INTO Languages(id, name, country) VALUES(542, "Cebuano", "Philippines");
INSERT INTO Languages(id, name, country) VALUES(543, "Ilocano", "Philippines");
INSERT INTO Languages(id, name, country) VALUES(544, "Bicol", "Philippines");
INSERT INTO Languages(id, name, country) VALUES(545, "Waray", "Philippines");
INSERT INTO Languages(id, name, country) VALUES(546, "Pampango", "Philippines");
INSERT INTO Languages(id, name, country) VALUES(547, "English", "Pitcairn Islands");
INSERT INTO Languages(id, name, country) VALUES(548, "Pitkern", "Pitcairn Islands");
INSERT INTO Languages VALUES(549, "Polish", "Poland", 96.2);
INSERT INTO Languages(id, name, country) VALUES(550, "Portuguese", "Portugal");
INSERT INTO Languages(id, name, country) VALUES(551, "Mirandese", "Portugal");
INSERT INTO Languages(id, name, country) VALUES(552, "Spanish", "Puerto Rico");
INSERT INTO Languages(id, name, country) VALUES(553, "English", "Puerto Rico");
INSERT INTO Languages(id, name, country) VALUES(554, "Arabic", "Qatar");
INSERT INTO Languages VALUES(555, "Romanian", "Romania", 85.4);
INSERT INTO Languages VALUES(556, "Hungarian", "Romania", 6.3);
INSERT INTO Languages VALUES(557, "Romany", "Romania", 1.2);
INSERT INTO Languages VALUES(558, "Russian", "Russia", 96.3);
INSERT INTO Languages VALUES(559, "Dolgang", "Russia", 5.3);
INSERT INTO Languages VALUES(560, "German", "Russia", 1.5);
INSERT INTO Languages VALUES(561, "Chechen", "Russia", 1);
INSERT INTO Languages VALUES(562, "Tatar", "Russia", 3);
INSERT INTO Languages VALUES(563, "Swahili", "Rwanda", 0.02);
INSERT INTO Languages(id, name, country) VALUES(564, "French", "Saint Barthelemy");
INSERT INTO Languages(id, name, country) VALUES(565, "English", "Saint Barthelemy");
INSERT INTO Languages(id, name, country) VALUES(566, "English", "Saint Helena, Ascension, and Tristan da Cunha");
INSERT INTO Languages(id, name, country) VALUES(567, "English", "Saint Kitts and Nevis");
INSERT INTO Languages(id, name, country) VALUES(568, "English", "Saint Lucia");
INSERT INTO Languages(id, name, country) VALUES(569, "French", "Saint Martin");
INSERT INTO Languages(id, name, country) VALUES(570, "English", "Saint Martin");
INSERT INTO Languages(id, name, country) VALUES(571, "Dutch", "Saint Martin");
INSERT INTO Languages(id, name, country) VALUES(572, "French Patois", "Saint Martin");
INSERT INTO Languages(id, name, country) VALUES(573, "Spanish", "Saint Martin");
INSERT INTO Languages(id, name, country) VALUES(574, "Papiamento", "Saint Martin");
INSERT INTO Languages(id, name, country) VALUES(575, "French", "Saint Pierre and Miquelon");
INSERT INTO Languages(id, name, country) VALUES(576, "English", "Saint Vincent and the Grenadines");
INSERT INTO Languages(id, name, country) VALUES(577, "Samoan", "Samoa");
INSERT INTO Languages(id, name, country) VALUES(578, "English", "Samoa");
INSERT INTO Languages(id, name, country) VALUES(579, "Italian", "San Marino");
INSERT INTO Languages VALUES(580, "Portuguese", "Sao Tome and Principe", 98.4);
INSERT INTO Languages VALUES(581, "Forro", "Sao Tome and Principe", 36.2);
INSERT INTO Languages VALUES(582, "Cabo Verdian", "Sao Tome and Principe", 8.5);
INSERT INTO Languages VALUES(583, "French", "Sao Tome and Principe", 6.8);
INSERT INTO Languages VALUES(584, "Angolar", "Sao Tome and Principe", 6.6);
INSERT INTO Languages VALUES(585, "English", "Sao Tome and Principe", 4.9);
INSERT INTO Languages VALUES(586, "Lunguie", "Sao Tome and Principe", 1);
INSERT INTO Languages(id, name, country) VALUES(587, "Arabic", "Saudi Arabia");
INSERT INTO Languages(id, name, country) VALUES(588, "French", "Senegal");
INSERT INTO Languages(id, name, country) VALUES(589, "Wolof", "Senegal");
INSERT INTO Languages(id, name, country) VALUES(590, "Pulaar", "Senegal");
INSERT INTO Languages(id, name, country) VALUES(591, "Jola", "Senegal");
INSERT INTO Languages(id, name, country) VALUES(592, "Mandinka", "Senegal");
INSERT INTO Languages VALUES(593, "Serbian", "Serbia", 88.1);
INSERT INTO Languages VALUES(594, "Hungarian", "Serbia", 3.4);
INSERT INTO Languages VALUES(595, "Bosnian", "Serbia", 1.9);
INSERT INTO Languages VALUES(596, "Romany", "Serbia", 1.4);
INSERT INTO Languages VALUES(597, "Seychellois Creole", "Seychelles", 89.1);
INSERT INTO Languages VALUES(598, "English", "Seychelles", 5.1);
INSERT INTO Languages VALUES(599, "French", "Seychelles", 0.7);
INSERT INTO Languages(id, name, country) VALUES(600, "English", "Sierra Leone");
INSERT INTO Languages(id, name, country) VALUES(601, "Mende", "Sierra Leone");
INSERT INTO Languages(id, name, country) VALUES(602, "Temne", "Sierra Leone");
INSERT INTO Languages(id, name, country) VALUES(603, "Krio", "Sierra Leone");
INSERT INTO Languages VALUES(604, "Mandarin", "Singapore", 36.3);
INSERT INTO Languages VALUES(605, "English", "Singapore", 29.8);
INSERT INTO Languages VALUES(606, "Malay", "Singapore", 11.9);
INSERT INTO Languages VALUES(607, "Hokkien", "Singapore", 8.1);
INSERT INTO Languages VALUES(608, "Tamil", "Singapore", 4.4);
INSERT INTO Languages VALUES(609, "Cantonese", "Singapore", 4.1);
INSERT INTO Languages VALUES(610, "Teochew", "Singapore", 3.2);
INSERT INTO Languages VALUES(611, "English", "Sint Maarten", 67.5);
INSERT INTO Languages VALUES(612, "Spanish", "Sint Maarten", 12.9);
INSERT INTO Languages VALUES(613, "Creole", "Sint Maarten", 8.2);
INSERT INTO Languages VALUES(614, "Dutch", "Sint Maarten", 4.2);
INSERT INTO Languages VALUES(615, "Papiamento", "Sint Maarten", 2.2);
INSERT INTO Languages VALUES(616, "French", "Sint Maarten", 1.5);
INSERT INTO Languages VALUES(617, "Slovak", "Slovakia", 78.6);
INSERT INTO Languages VALUES(618, "Hungarian", "Slovakia", 9.4);
INSERT INTO Languages VALUES(619, "Roma", "Slovakia", 2.3);
INSERT INTO Languages VALUES(620, "Ruthenian", "Slovakia", 1);
INSERT INTO Languages VALUES(621, "Slovenian", "Slovenia", 91.1);
INSERT INTO Languages VALUES(622, "Serbo-Croatian", "Slovenia", 4.5);
INSERT INTO Languages(id, name, country) VALUES(623, "Italian", "Slovenia");
INSERT INTO Languages(id, name, country) VALUES(624, "Hungarian", "Slovenia");
INSERT INTO Languages(id, name, country) VALUES(625, "English", "Solomon Islands");
INSERT INTO Languages(id, name, country) VALUES(626, "Somali", "Somalia");
INSERT INTO Languages(id, name, country) VALUES(627, "Arabic", "Somalia");
INSERT INTO Languages(id, name, country) VALUES(628, "Italian", "Somalia");
INSERT INTO Languages(id, name, country) VALUES(629, "English", "Somalia");
INSERT INTO Languages VALUES(630, "IsiZulu", "South Africa", 22.7);
INSERT INTO Languages VALUES(631, "IsiXhosa", "South Africa", 16);
INSERT INTO Languages VALUES(632, "Afrikaans", "South Africa", 13.5);
INSERT INTO Languages VALUES(633, "English", "South Africa", 9.6);
INSERT INTO Languages VALUES(634, "Sepedi", "South Africa", 9.1);
INSERT INTO Languages VALUES(635, "Setswana", "South Africa", 8);
INSERT INTO Languages VALUES(636, "Sesotho", "South Africa", 7.6);
INSERT INTO Languages VALUES(637, "Xitsonga", "South Africa", 4.5);
INSERT INTO Languages VALUES(638, "Tshivenda", "South Africa", 2.4);
INSERT INTO Languages(id, name, country) VALUES(639, "English", "South Sudan");
INSERT INTO Languages(id, name, country) VALUES(640, "Arabic", "South Sudan");
INSERT INTO Languages(id, name, country) VALUES(641, "Nuer", "South Sudan");
INSERT INTO Languages(id, name, country) VALUES(642, "Bari", "South Sudan");
INSERT INTO Languages(id, name, country) VALUES(643, "Zande", "South Sudan");
INSERT INTO Languages(id, name, country) VALUES(644, "Shilluk", "South Sudan");
INSERT INTO Languages VALUES(645, "Castilian Spanish", "Spain", 74);
INSERT INTO Languages VALUES(646, "Catalan", "Spain", 17);
INSERT INTO Languages VALUES(647, "Galician", "Spain", 7);
INSERT INTO Languages VALUES(648, "Sinhala", "Sri Lanka", 74);
INSERT INTO Languages VALUES(649, "Tamil", "Sri Lanka", 18);
INSERT INTO Languages(id, name, country) VALUES(650, "Arabic", "Sudan");
INSERT INTO Languages(id, name, country) VALUES(651, "English", "Sudan");
INSERT INTO Languages(id, name, country) VALUES(652, "Nubian", "Sudan");
INSERT INTO Languages(id, name, country) VALUES(653, "Ta Bedawie", "Sudan");
INSERT INTO Languages(id, name, country) VALUES(654, "Fur", "Sudan");
INSERT INTO Languages(id, name, country) VALUES(655, "Dutch", "Suriname");
INSERT INTO Languages(id, name, country) VALUES(656, "English", "Suriname");
INSERT INTO Languages(id, name, country) VALUES(657, "Sranang Tongo", "Suriname");
INSERT INTO Languages(id, name, country) VALUES(658, "Caribbean Hindustani", "Suriname");
INSERT INTO Languages(id, name, country) VALUES(659, "Javanese", "Suriname");
INSERT INTO Languages(id, name, country) VALUES(660, "Norwegian", "Svalbard");
INSERT INTO Languages(id, name, country) VALUES(661, "Russian", "Svalbard");
INSERT INTO Languages(id, name, country) VALUES(662, "English", "Swaziland");
INSERT INTO Languages(id, name, country) VALUES(663, "Swedish", "Sweden");
INSERT INTO Languages VALUES(664, "German", "Switzerland", 64.9);
INSERT INTO Languages VALUES(665, "French", "Switzerland", 22.6);
INSERT INTO Languages VALUES(666, "Italian", "Switzerland", 8.3);
INSERT INTO Languages VALUES(667, "Serbo-Croatian", "Switzerland", 2.5);
INSERT INTO Languages VALUES(668, "Albanian", "Switzerland", 2.6);
INSERT INTO Languages VALUES(669, "Portuguese", "Switzerland", 3.4);
INSERT INTO Languages VALUES(670, "Spanish", "Switzerland", 2.2);
INSERT INTO Languages VALUES(671, "English", "Switzerland", 4.6);
INSERT INTO Languages VALUES(672, "Romansch", "Switzerland", 0.5);
INSERT INTO Languages(id, name, country) VALUES(673, "Arabic", "Syria");
INSERT INTO Languages(id, name, country) VALUES(674, "Kurdish", "Syria");
INSERT INTO Languages(id, name, country) VALUES(675, "Armenian", "Syria");
INSERT INTO Languages(id, name, country) VALUES(676, "Aramaic", "Syria");
INSERT INTO Languages(id, name, country) VALUES(677, "Circassian French", "Syria");
INSERT INTO Languages(id, name, country) VALUES(678, "English", "Syria");
INSERT INTO Languages(id, name, country) VALUES(679, "Mandarin Chinese", "Taiwan");
INSERT INTO Languages(id, name, country) VALUES(680, "Taiwanese", "Taiwan");
INSERT INTO Languages(id, name, country) VALUES(681, "Tajik", "Tajikistan");
INSERT INTO Languages(id, name, country) VALUES(682, "Kiunguja", "Tanzania");
INSERT INTO Languages(id, name, country) VALUES(683, "English", "Tanzania");
INSERT INTO Languages(id, name, country) VALUES(684, "Arabic", "Tanzania");
INSERT INTO Languages VALUES(685, "Thai", "Thailand", 90.7);
INSERT INTO Languages VALUES(686, "Burmese", "Thailand", 1.3);
INSERT INTO Languages(id, name, country) VALUES(687, "Tetum", "Timor-Leste");
INSERT INTO Languages(id, name, country) VALUES(688, "Portuguese", "Timor-Leste");
INSERT INTO Languages(id, name, country) VALUES(689, "Indonesian", "Timor-Leste");
INSERT INTO Languages(id, name, country) VALUES(690, "English", "Timor-Leste");
INSERT INTO Languages(id, name, country) VALUES(691, "French", "Togo");
INSERT INTO Languages VALUES(692, "Tokelauan", "Tokelau", 93.5);
INSERT INTO Languages VALUES(693, "English", "Tokelau", 58.9);
INSERT INTO Languages VALUES(694, "Samoan", "Tokelau", 45.5);
INSERT INTO Languages VALUES(695, "Tuvaluan", "Tokelau", 11.6);
INSERT INTO Languages VALUES(696, "Kiribati", "Tokelau", 2.7);
INSERT INTO Languages VALUES(697, "Tongan", "Tonga", 10.7);
INSERT INTO Languages VALUES(698, "English", "Tonga", 1.2);
INSERT INTO Languages(id, name, country) VALUES(699, "English", "Trinidad and Tobago");
INSERT INTO Languages(id, name, country) VALUES(700, "Caribbean Hindustani", "Trinidad and Tobago");
INSERT INTO Languages(id, name, country) VALUES(701, "French", "Trinidad and Tobago");
INSERT INTO Languages(id, name, country) VALUES(702, "Spanish", "Trinidad and Tobago");
INSERT INTO Languages(id, name, country) VALUES(703, "Chinese", "Trinidad and Tobago");
INSERT INTO Languages(id, name, country) VALUES(704, "Arabic", "Tunisia");
INSERT INTO Languages(id, name, country) VALUES(705, "French", "Tunisia");
INSERT INTO Languages(id, name, country) VALUES(706, "Berber", "Tunisia");
INSERT INTO Languages(id, name, country) VALUES(707, "Turkish", "Turkey");
INSERT INTO Languages(id, name, country) VALUES(708, "Kurdish", "Turkey");
INSERT INTO Languages VALUES(709, "Turkmen", "Turkmenistan", 72);
INSERT INTO Languages VALUES(710, "Russian", "Turkmenistan", 12);
INSERT INTO Languages VALUES(711, "Uzbek", "Turkmenistan", 9);
INSERT INTO Languages(id, name, country) VALUES(712, "English", "Turks and Caicos Islands");
INSERT INTO Languages(id, name, country) VALUES(713, "Tuvaluan", "Tuvalu");
INSERT INTO Languages(id, name, country) VALUES(714, "English", "Tuvalu");
INSERT INTO Languages(id, name, country) VALUES(715, "Samoan", "Tuvalu");
INSERT INTO Languages(id, name, country) VALUES(716, "Kiribati", "Tuvalu");
INSERT INTO Languages(id, name, country) VALUES(717, "English", "Uganda");
INSERT INTO Languages(id, name, country) VALUES(718, "Swahili", "Uganda");
INSERT INTO Languages(id, name, country) VALUES(719, "Arabic", "Uganda");
INSERT INTO Languages VALUES(720, "Ukrainian", "Ukraine", 67);
INSERT INTO Languages VALUES(721, "Russian", "Ukraine", 24);
INSERT INTO Languages(id, name, country) VALUES(722, "Arabic", "United Arab Emirates");
INSERT INTO Languages(id, name, country) VALUES(723, "Persian", "United Arab Emirates");
INSERT INTO Languages(id, name, country) VALUES(724, "English", "United Arab Emirates");
INSERT INTO Languages(id, name, country) VALUES(725, "Hindi", "United Arab Emirates");
INSERT INTO Languages(id, name, country) VALUES(726, "Urdu", "United Arab Emirates");
INSERT INTO Languages(id, name, country) VALUES(727, "English", "United Kingdom");
INSERT INTO Languages VALUES(728, "English", "United States", 82.1);
INSERT INTO Languages VALUES(729, "Spanish", "United States", 10.7);
INSERT INTO Languages(id, name, country) VALUES(730, "Spanish", "Uruguay");
INSERT INTO Languages(id, name, country) VALUES(731, "Portunol", "Uruguay");
INSERT INTO Languages(id, name, country) VALUES(732, "Brazilero", "Uruguay");
INSERT INTO Languages VALUES(733, "Uzbek", "Uzbekistan", 74.3);
INSERT INTO Languages VALUES(734, "Russian", "Uzbekistan", 14.2);
INSERT INTO Languages VALUES(735, "Tajik", "Uzbekistan", 4.4);
INSERT INTO Languages VALUES(736, "Bislama", "Vanuatu", 33.7);
INSERT INTO Languages VALUES(737, "English", "Vanuatu", 2);
INSERT INTO Languages VALUES(738, "French", "Vanuatu", 0.6);
INSERT INTO Languages(id, name, country) VALUES(739, "Spanish", "Venezuela");
INSERT INTO Languages(id, name, country) VALUES(740, "Vietnamese", "Vietnam");
INSERT INTO Languages(id, name, country) VALUES(741, "English", "Vietnam");
INSERT INTO Languages(id, name, country) VALUES(742, "Chinese", "Vietnam");
INSERT INTO Languages VALUES(743, "English", "Virgin Islands", 74.7);
INSERT INTO Languages VALUES(744, "Wallisian", "Wallis and Futuna", 58.9);
INSERT INTO Languages VALUES(745, "Futunian", "Wallis and Futuna", 30.1);
INSERT INTO Languages VALUES(746, "French", "Wallis and Futuna", 10.8);
INSERT INTO Languages(id, name, country) VALUES(747, "Arabic", "West Bank");
INSERT INTO Languages(id, name, country) VALUES(748, "Hebrew", "West Bank");
INSERT INTO Languages(id, name, country) VALUES(749, "English", "West Bank");
INSERT INTO Languages(id, name, country) VALUES(750, "Standard Arabic", "Western Sahara");
INSERT INTO Languages(id, name, country) VALUES(751, "Hassaniya Arabic", "Western Sahara");
INSERT INTO Languages(id, name, country) VALUES(752, "Moroccan Arabic", "Western Sahara");
INSERT INTO Languages(id, name, country) VALUES(753, "Arabic", "Yemen");
INSERT INTO Languages VALUES(754, "Bembe", "Zambia", 33.4);
INSERT INTO Languages VALUES(755, "Nyanja", "Zambia", 14.7);
INSERT INTO Languages VALUES(756, "Tonga", "Zambia", 11.4);
INSERT INTO Languages VALUES(757, "Lozi", "Zambia", 5.5);
INSERT INTO Languages VALUES(758, "Chewa", "Zambia", 4.5);
INSERT INTO Languages VALUES(759, "Nsenga", "Zambia", 2.9);
INSERT INTO Languages VALUES(760, "Tumbuka", "Zambia", 2.5);
INSERT INTO Languages VALUES(761, "Lunda", "Zambia", 1.9);
INSERT INTO Languages VALUES(762, "Kaonde", "Zambia", 1.8);
INSERT INTO Languages VALUES(763, "Lala", "Zambia", 1.8);
INSERT INTO Languages VALUES(764, "Lamba", "Zambia", 1.8);
INSERT INTO Languages VALUES(765, "English", "Zambia", 1.7);
INSERT INTO Languages VALUES(766, "Luvale", "Zambia", 1.5);
INSERT INTO Languages VALUES(767, "Mambwe", "Zambia", 1.3);
INSERT INTO Languages VALUES(768, "Namwanga", "Zambia", 1.2);
INSERT INTO Languages VALUES(769, "Lenje", "Zambia", 1.1);
INSERT INTO Languages VALUES(770, "Bisa", "Zambia", 1);
INSERT INTO Languages(id, name, country) VALUES(771, "English", "Zimbabwe");
INSERT INTO Languages(id, name, country) VALUES(772, "Shona", "Zimbabwe");
INSERT INTO Languages(id, name, country) VALUES(773, "Sindebele", "Zimbabwe");
